// Wordle uses two separate lists, and conflating them is what made an
// earlier version reject HELLO, PIZZA and CRANE outright.
//
//   ANSWERS  - the small curated set a puzzle is actually drawn from. Common,
//              unambiguous words only, so a solvable puzzle is always fair.
//   GUESSES  - the much larger set a player is *allowed to type*. Being
//              permissive here costs nothing (a bad guess only wastes the
//              player's own turn) while being strict is infuriating.
//
// Every answer is also a legal guess. Sourced from the system dictionary
// plus regular plural/third-person forms, which that dictionary omits.

export const ANSWERS = [
  'ABOUT', 'ABOVE', 'ACTOR', 'ACUTE', 'ADMIT', 'ADOPT', 'ADULT', 'AFTER',
  'AGAIN', 'AGENT', 'AGREE', 'AHEAD', 'ALARM', 'ALBUM', 'ALERT', 'ALIKE',
  'ALIVE', 'ALLOW', 'ALONE', 'ALONG', 'ALTER', 'AMONG', 'ANGER', 'ANGLE',
  'ANGRY', 'ANKLE', 'APART', 'APPLE', 'APPLY', 'ARENA', 'ARGUE', 'ARISE',
  'ARRAY', 'ARROW', 'ASIDE', 'ASSET', 'AUDIO', 'AUDIT', 'AVOID', 'AWAKE',
  'AWARD', 'AWARE', 'BADLY', 'BAKER', 'BASIC', 'BEACH', 'BEGAN', 'BEGIN',
  'BEING', 'BELOW', 'BENCH', 'BIRTH', 'BLACK', 'BLADE', 'BLAME', 'BLANK',
  'BLAST', 'BLEND', 'BLIND', 'BLOCK', 'BLOOD', 'BOARD', 'BOAST', 'BONUS',
  'BOOST', 'BOUND', 'BRAIN', 'BRAND', 'BRASS', 'BRAVE', 'BREAD', 'BREAK',
  'BREED', 'BRICK', 'BRIEF', 'BRING', 'BROAD', 'BROKE', 'BROWN', 'BRUSH',
  'BUILD', 'BUILT', 'BUNCH', 'BURST', 'BUYER', 'CABLE', 'CANDY', 'CARGO',
  'CARRY', 'CARVE', 'CATCH', 'CAUSE', 'CHAIN', 'CHAIR', 'CHALK', 'CHARM',
  'CHART', 'CHASE', 'CHEAP', 'CHECK', 'CHEST', 'CHIEF', 'CHILD', 'CHOSE',
  'CIVIL', 'CLAIM', 'CLASS', 'CLEAN', 'CLEAR', 'CLICK', 'CLIFF', 'CLIMB',
  'CLOCK', 'CLOSE', 'CLOUD', 'COACH', 'COAST', 'COUNT', 'COURT', 'COVER',
  'CRACK', 'CRAFT', 'CRASH', 'CRAZY', 'CREAM', 'CRIME', 'CROSS', 'CROWD',
  'CROWN', 'CRUEL', 'CRUSH', 'CURVE', 'CYCLE', 'DAILY', 'DAIRY', 'DANCE',
  'DEALT', 'DEATH', 'DEBUT', 'DELAY', 'DENSE', 'DEPTH', 'DIRTY', 'DOING',
  'DOUBT', 'DOZEN', 'DRAFT', 'DRAIN', 'DRAMA', 'DRAWN', 'DREAM', 'DRESS',
  'DRIED', 'DRILL', 'DRINK', 'DRIVE', 'DROVE', 'DYING', 'EAGER', 'EARLY',
  'EARTH', 'EIGHT', 'ELBOW', 'ELDER', 'ELITE', 'EMPTY', 'ENEMY', 'ENJOY',
  'ENTER', 'ENTRY', 'EQUAL', 'ERROR', 'EVENT', 'EVERY', 'EXACT', 'EXIST',
  'EXTRA', 'FAITH', 'FALSE', 'FANCY', 'FAULT', 'FAVOR', 'FEAST', 'FENCE',
  'FEVER', 'FIBER', 'FIELD', 'FIFTH', 'FIFTY', 'FIGHT', 'FINAL', 'FIRST',
  'FIXED', 'FLAME', 'FLASH', 'FLEET', 'FLESH', 'FLOAT', 'FLOOR', 'FLOUR',
  'FLUID', 'FOCUS', 'FORCE', 'FORGE', 'FORTH', 'FORTY', 'FORUM', 'FOUND',
  'FRAME', 'FRANK', 'FRAUD', 'FRESH', 'FRONT', 'FROST', 'FRUIT', 'FULLY',
  'FUNNY', 'GIANT', 'GIVEN', 'GLASS', 'GLOBE', 'GLORY', 'GOING', 'GRACE',
  'GRADE', 'GRAIN', 'GRAND', 'GRANT', 'GRAPE', 'GRAPH', 'GRASP', 'GRASS',
  'GRAVE', 'GREAT', 'GREEN', 'GRIEF', 'GROSS', 'GROUP', 'GROWN', 'GUARD',
  'GUESS', 'GUEST', 'GUIDE', 'HABIT', 'HAPPY', 'HARSH', 'HASTE', 'HEART',
  'HEAVY', 'HENCE', 'HOBBY', 'HONEY', 'HONOR', 'HORSE', 'HOTEL', 'HOUSE',
  'HUMAN', 'HUMOR', 'HURRY', 'IDEAL', 'IMAGE', 'IMPLY', 'INDEX', 'INNER',
  'INPUT', 'IRONY', 'ISSUE', 'IVORY', 'JOINT', 'JUDGE', 'JUICE', 'KNEEL',
  'KNIFE', 'KNOCK', 'KNOWN', 'LABEL', 'LABOR', 'LARGE', 'LASER', 'LATER',
  'LAUGH', 'LAYER', 'LEARN', 'LEASE', 'LEAST', 'LEAVE', 'LEGAL', 'LEMON',
  'LEVEL', 'LIGHT', 'LIMIT', 'LINEN', 'LIVER', 'LOCAL', 'LODGE', 'LOGIC',
  'LOOSE', 'LOWER', 'LOYAL', 'LUCKY', 'LUNAR', 'LUNCH', 'MAGIC', 'MAJOR',
  'MAKER', 'MAPLE', 'MARCH', 'MARSH', 'MATCH', 'MAYBE', 'MAYOR', 'MEANT',
  'MEDAL', 'MEDIA', 'MERCY', 'MERGE', 'MERIT', 'METAL', 'METER', 'MIDST',
  'MIGHT', 'MINOR', 'MINUS', 'MIXED', 'MODEL', 'MONEY', 'MONTH', 'MORAL',
  'MOTOR', 'MOUNT', 'MOUSE', 'MOUTH', 'MOVIE', 'MUSIC', 'NAKED', 'NASTY',
  'NERVE', 'NEVER', 'NEWLY', 'NIGHT', 'NOBLE', 'NOISE', 'NORTH', 'NOTED',
  'NOVEL', 'NURSE', 'OCCUR', 'OCEAN', 'OFFER', 'OFTEN', 'OLIVE', 'ONION',
  'ORBIT', 'ORDER', 'ORGAN', 'OTHER', 'OUGHT', 'OUNCE', 'OUTER', 'OWNER',
  'PAINT', 'PANEL', 'PANIC', 'PAPER', 'PARTY', 'PASTE', 'PATCH', 'PAUSE',
  'PEACE', 'PEARL', 'PEDAL', 'PENNY', 'PHASE', 'PHONE', 'PHOTO', 'PIANO',
  'PIECE', 'PILOT', 'PITCH', 'PIVOT', 'PLACE', 'PLAIN', 'PLANE', 'PLANT',
  'PLATE', 'POINT', 'POUND', 'POWER', 'PRESS', 'PRICE', 'PRIDE', 'PRIME',
  'PRINT', 'PRIOR', 'PRIZE', 'PROOF', 'PROUD', 'PROVE', 'PUPIL', 'PURSE',
  'QUEEN', 'QUERY', 'QUEST', 'QUEUE', 'QUICK', 'QUIET', 'QUITE', 'QUOTA',
  'QUOTE', 'RADAR', 'RADIO', 'RAISE', 'RANCH', 'RANGE', 'RAPID', 'RATIO',
  'REACH', 'REACT', 'READY', 'REALM', 'REBEL', 'REFER', 'RELAX', 'RELAY',
  'REPLY', 'RIDER', 'RIDGE', 'RIGHT', 'RIGID', 'RIVAL', 'RIVER', 'ROAST',
  'ROBIN', 'ROBOT', 'ROCKY', 'ROMAN', 'ROUGH', 'ROUND', 'ROUTE', 'ROYAL',
  'RURAL', 'SADLY', 'SAINT', 'SALAD', 'SANDY', 'SAUCE', 'SCALE', 'SCENE',
  'SCOPE', 'SCORE', 'SCOUT', 'SENSE', 'SERVE', 'SEVEN', 'SHADE', 'SHAKE',
  'SHALL', 'SHAME', 'SHAPE', 'SHARE', 'SHARP', 'SHEEP', 'SHEET', 'SHELF',
  'SHELL', 'SHIFT', 'SHINE', 'SHIRT', 'SHOCK', 'SHOOT', 'SHORE', 'SHORT',
  'SHOUT', 'SIGHT', 'SILLY', 'SINCE', 'SIXTH', 'SIXTY', 'SKILL', 'SLEEP',
  'SLIDE', 'SLOPE', 'SMALL', 'SMART', 'SMILE', 'SMOKE', 'SNAKE', 'SOLAR',
  'SOLID', 'SOLVE', 'SORRY', 'SOUND', 'SOUTH', 'SPACE', 'SPARE', 'SPARK',
  'SPEAK', 'SPEED', 'SPEND', 'SPENT', 'SPICE', 'SPINE', 'SPLIT', 'SPOKE',
  'SPORT', 'SQUAD', 'STACK', 'STAFF', 'STAGE', 'STAIR', 'STAKE', 'STAMP',
  'STAND', 'STARE', 'START', 'STATE', 'STEAM', 'STEEL', 'STEEP', 'STEER',
  'STICK', 'STIFF', 'STILL', 'STOCK', 'STONE', 'STOOD', 'STORE', 'STORM',
  'STORY', 'STOVE', 'STRAP', 'STRAW', 'STRIP', 'STUCK', 'STUDY', 'STUFF',
  'STYLE', 'SUGAR', 'SUITE', 'SUPER', 'SWEAR', 'SWEEP', 'SWEET', 'SWIFT',
  'SWING', 'SWORD', 'TABLE', 'TAKEN', 'TASTE', 'TEACH', 'TENTH', 'THANK',
  'THEFT', 'THEIR', 'THEME', 'THERE', 'THESE', 'THICK', 'THIEF', 'THING',
  'THINK', 'THIRD', 'THOSE', 'THREE', 'THREW', 'THROW', 'THUMB', 'TIGER',
  'TIGHT', 'TIRED', 'TITLE', 'TODAY', 'TOKEN', 'TOOTH', 'TOPIC', 'TOTAL',
  'TOUCH', 'TOUGH', 'TOWEL', 'TOWER', 'TRACE', 'TRACK', 'TRADE', 'TRAIL',
  'TRAIN', 'TREAT', 'TREND', 'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TRUCK',
  'TRULY', 'TRUNK', 'TRUST', 'TRUTH', 'TWICE', 'TWIST', 'UNCLE', 'UNDER',
  'UNION', 'UNITE', 'UNITY', 'UNTIL', 'UPPER', 'UPSET', 'URBAN', 'USAGE',
  'USUAL', 'VALID', 'VALUE', 'VAPOR', 'VAULT', 'VENUE', 'VERSE', 'VIDEO',
  'VIRUS', 'VISIT', 'VITAL', 'VIVID', 'VOCAL', 'VOICE', 'WAGON', 'WAIST',
  'WASTE', 'WATCH', 'WATER', 'WEARY', 'WEIRD', 'WHEAT', 'WHEEL', 'WHERE',
  'WHICH', 'WHILE', 'WHITE', 'WHOLE', 'WHOSE', 'WIDEN', 'WIDOW', 'WIDTH',
  'WITCH', 'WOMAN', 'WORLD', 'WORRY', 'WORSE', 'WORST', 'WORTH', 'WOULD',
  'WOUND', 'WRIST', 'WRITE', 'WRONG', 'WROTE', 'YIELD', 'YOUNG', 'YOURS',
  'YOUTH', 'ZEBRA',
]

// Packed as fixed-width 5-character records rather than a quoted array:
// same 12745 words in ~62KB instead of ~112KB of source.
const PACKED_GUESSES = `
  AALIIABACAABACKABACSABAFFABAFTABASEABASHABASKABASSABATEABAVEABAZEABBASABBEYABBOT
  ABDALABDATABEAMABEARABEDSABELEABETSABEYSABHORABIDEABIDIABILOABIRSABKARABLERABLES
  ABLOWABLYSABMHOABNETABODEABODYABOHMABOILABOMAABOONABORDABORTABOUTABOVEABOXSABRET
  ABRIMABRINABSITABUNAABURAABUSEABUTSABUZZABWABABYSMABYSSACANAACAPUACARAACARIACATE
  ACCASACCOYACEDYACERBACHARACHERACHESACHORACHYSACIDSACIERACKERACKEYACLESACLYSACMES
  ACMICACNESACOCKACOINACOLDACOMAACONEACORNACORSACREDACRESACRIDACRONACRYLACTASACTIN
  ACTONACTORACTUSACUTEACYLSADADSADAGEADAPTADATIADATSADAWEADAWNADAWSADAYSADDASADDAX
  ADDEDADDERADDLEADEADADEEMADEEPADEPTADETSADFIXADIEUADIONADITSADJAGADLAYADLETADMAN
  ADMINADMISADMITADMIXADNEXADOBEADOPTADOREADORNADOWNADOXYADOZEADPAOADRIPADROPADRUE
  ADRYSADULTADUNCADUSKADUSTADYTAADZERADZESAEGISAEONSAERICAERIEAEROSAERYSAEVIAAFACE
  AFARAAFARSAFEARAFFASAFFIXAFFYSAFIREAFLATAFLOWAFOAMAFOOTAFOREAFOULAFRETAFTERAGAIN
  AGALSAGAMAAGAMIAGAMYAGAPEAGARSAGASPAGATEAGATYAGAZEAGEDSAGEESAGENSAGENTAGERSAGGER
  AGGRYAGGURAGHASAGILEAGINGAGIOSAGISTAGITAAGLASAGLETAGLEYAGLOWAGNELAGNUSAGOGEAGOGS
  AGOHOAGONEAGONSAGONYAGORAAGRAHAGRALAGREEAGRESAGRIAAGRINAGROMAGSAMAGUASAGUESAGUEY
  AGUSHAGUSTAHEADAHEAPAHEMSAHEYSAHINDAHINTAHONGAHOYSAHSANAHULLAHUMSAHUNTAHURAAHUSH
  AHWALAIDERAIDESAIELSAILESAILLTAIMERAINOIAINTSAIONSAIRANAIRERAIRESAIRTSAIRYSAISLE
  AITCHAIWANAIZLEAJAJAAJARIAJARSAJAVAAJHARAJOGSAKALAAKASAAKEBIAKEESAKEKIAKEYSAKIAS
  AKINSAKNEEAKOVSAKPEKAKRASAKULEAKUNDALACKALADAALALAALAMOALANDALANIALANSALARMALARS
  ALARYALASSALATEALBANALBASALBEEALBESALBUMALBUSALCOSALDERALDIMALDOLALEAKALECSALEES
  ALEFSALEFTALEMSALENSALEPHALERTALFASALFETALGAEALGALALGASALGICALGIDALGINALGORALGUM
  ALIASALIBIALIENALIFSALIGNALIKEALIMAALINSALISHALISOALISPALISTALITEALITSALIVEALKYD
  ALKYLALKYSALLANALLAYALLERALLEYALLOTALLOWALLOYALLYLALLYSALMASALMESALMONALMSSALMUD
  ALMUGALODSALODYALOEDALOESALOFTALOGYALOIDALOINALOMAALONEALONGALOOFALOPSALOSEALOUD
  ALOWEALOWSALPHAALSOSALTARALTERALTHOALTINALTOSALTUNALULAALUMSALUREALUTAALVARALVUS
  ALWAYAMAASAMAGAAMAHSAMAINAMALAAMANGAMANIAMAPAAMARSAMASSAMAZEAMBANAMBARAMBASAMBAY
  AMBERAMBITAMBLEAMBONAMBOSAMBRYAMEEDAMEENAMELUAMENDAMENEAMENSAMENTAMHARAMICEAMICS
  AMIDEAMIDOAMIDSAMILSAMINEAMINIAMINOAMINSAMIRSAMISSAMITYAMLASAMLISAMMANAMMASAMMER
  AMMOSAMMUSAMNIAAMNICAMOKEAMOKSAMOLEAMONGAMORSAMORTAMOURAMOVEAMPERAMPLEAMPLYAMPUL
  AMPYXAMRASAMSELAMUCKAMULAAMUSEAMUZEAMVISAMYLOAMYLSANABOANALSANAMAANAMSANANAANANS
  ANAYSANBASANCONANDASANEARANELEANENDANENTANESSANEWSANGELANGERANGLEANGORANGOSANGRY
  ANGSTANIGHANILEANILSANIMAANIMEANIMIANIONANISEANISSANJANANKEEANKERANKHSANKLEANKUS
  ANNALANNASANNATANNETANNEXANNOYANNULANOASANODEANOILANOLEANOLIANOMYANONSANSARANSAS
  ANSUSANTALANTASANTESANTICANTISANTRAANTREANTUSANURYANUSSANVILAORTAAPACEAPAIDAPARS
  APARTAPEAKAPERSAPERTAPERYAPEXSAPHIDAPIANAPIINAPIISAPINGAPIOSAPISHAPISMAPNEAAPODS
  APOOPAPORTAPOUTAPPAYAPPETAPPLEAPPLYAPRONAPSESAPSISAPTLYAQUASAQUOSARABAARACAARADO
  ARADSARAINARAKEARARAARARSARATIARBASARBORARCASARCHEARCHSARCHYARDEBARDORARDRIARDUS
  AREADAREALAREARAREASAREDSAREEKAREELARENAARENDARENGARENTARETEARGALARGELARGILARGOL
  ARGONARGOSARGOTARGUEARHARARHATARIASARIDSARIELARILSARIOTARISEARISTARITEARJUNARLES
  ARMEDARMERARMETARMILARMORARMSSARMYSARNASARNEEARNISARNUTAROARAROCKAROIDAROMAAROON
  AROSEAROWSARPENARRAHARRASARRAUARRAYARRIEARRISARROWARSESARSISARSLEARSONARSYLARTAL
  ARTARARTELARTHAARTYSARUISARUKEARUPAARUSAARVALARVELARYLSARZANARZUNASAKSASALEASANA
  ASCANASCIIASCISASCONASCOTASCRYASCUSASDICASEMSASHENASHESASHETASHURASHYSASIDEASKAR
  ASKERASKEWASKIPASKOSASLOPASOAKASOKAASOKSASOPSASORSASPENASPERASPICASSAIASSAYASSES
  ASSETASSISASTASASTAYASTERASTIRASTORASWAYASWIMASYLAATAPSATAVIATAXYATEFSATELOATESS
  ATHARATILTATIPSATISSATLASATLEEATLESATMANATMASATMIDATMOSATOKEATOLLATOMSATOMYATONE
  ATONYATOPSATOPYATOURATRIAATRIPATRYSATTARATTASATTERATTICATTIDATULEATUNEATWINATWOS
  ATYPYAUBESAUCASAUDIOAUDITAUGENAUGERAUGESAUGHSAUGHTAUGURAULAEAULASAULDSAULICAULOI
  AULOSAULUSAUMILAUNESAUNTSAURAEAURALAURARAURASAURICAURINAURIRAURUMAURYLAUSUSAUTEM
  AUTESAUTOSAUXINAVAHIAVAILAVALSAVASTAVENSAVERAAVERSAVERTAVIANAVICKAVIDSAVINEAVISO
  AVOIDAVOWSAWABIAWAFTAWAGSAWAITAWAKEAWALDAWALTAWANEAWARDAWAREAWASHAWATSAWAVEAWAYS
  AWBERAWEEKAWEELAWEESAWESTAWETOAWFULAWFUSAWHETAWHIRAWIDEAWINGAWINKAWINSAWIWIAWNED
  AWNERAWNYSAWOKEAWORKAWRYSAXALSAXEDSAXESSAXIALAXILEAXILSAXINEAXIOMAXIONAXISSAXITE
  AXLEDAXLESAXMANAXOIDAXONSAYAHSAYELPAYINSAYLETAYLLUAYONDAYONTAYOUSAZIDEAZINEAZOCH
  AZOFYAZOICAZOLEAZONSAZOTEAZOTHAZOXSAZOXYAZUREAZURYAZYMEBAALSBAARSBABAIBABASBABBY
  BABESBABOOBABULBABUSBABYSBACAOBACCABACHEBACHSBACKSBACONBADANBADESBADGEBADLYBAFFS
  BAFFYBAFTABAFTSBAGASBAGELBAGGYBAGOSBAGREBAHANBAHARBAHAYBAHOEBAHOOBAHOSBAHTSBAHUR
  BAHUTBAILSBAINSBAIOCBAIRNBAITHBAITSBAIZEBAJANBAJRABAJRIBAKALBAKASBAKEDBAKENBAKER
  BAKESBAKIEBAKLIBAKUSBALAIBALAOBALASBALDSBALDYBALEIBALERBALESBALISBALKSBALKYBALLI
  BALLSBALLYBALMSBALMYBALOOBALOWBALSABALUSBALUTBALZABANAKBANALBANATBANCABANCOBANCS
  BANDABANDEBANDIBANDOBANDSBANDYBANESBANGABANGEBANGSBANIGBANISBANJOBANKSBANKYBANNS
  BANTSBANTYBANYABARADBARASBARBEBARBSBARDOBARDSBARDYBARERBARESBARFFBARGEBARGHBARIA
  BARICBARIDBARIEBARISBARITBARKSBARKYBARMSBARMYBARNSBARNYBAROIBARONBARRABARRYBARSE
  BARTHBARUSBARYEBASALBASEDBASESBASHSBASICBASILBASINBASISBASKSBASONBASOSBASSOBASSS
  BASTABASTEBASTOBASTSBATADBATCHBATEABATEDBATELBATERBATESBATHEBATHSBATIKBATONBATSS
  BATTABATTSBATTYBATZSBAUCHBAUDSBAULSBAUNOBAUNSBAUTABAVINBAWDSBAWLSBAWNSBAYALBAYAS
  BAYEDBAYOKBAYOUBAZESBAZOOBEACHBEADSBEADYBEAKSBEAKYBEALABEALSBEAMSBEAMYBEANOBEANS
  BEANTBEANYBEARDBEARMBEARSBEASTBEATABEATHBEATSBEAUSBEAUTBEAUXBEBARBEBATBEBAYBEBED
  BEBOGBEBOPBECAPBECKSBECRYBECUTBEDADBEDAYBEDELBEDENBEDEWBEDIMBEDINBEDIPBEDOGBEDOT
  BEDUBBEDURBEDYEBEECHBEEFSBEEFYBEEKSBEENSBEERSBEERYBEESSBEESTBEETHBEETSBEETYBEEVE
  BEFANBEFITBEFOGBEFOPBEGADBEGANBEGARBEGATBEGAYBEGEMBEGETBEGINBEGOBBEGOSBEGUMBEGUN
  BEGUTBEHAPBEHENBEHNSBEICEBEIGEBEINGBEIRABEISABEJANBEJELBEJIGBEKAHBEKKOBELAHBELAM
  BELARBELASBELAYBELCHBELDSBELEEBELGABELIEBELLEBELLSBELLYBELOWBELTSBELVEBELYSBEMAD
  BEMANBEMARBEMASBEMATBEMIXBEMUDBENABBENASBENCHBENDABENDSBENDYBENESBENETBENGSBENIS
  BENJSBENJYBENNEBENNSBENNYBENOSBENSHBENTSBENTYBENZOBEODEBEPATBEPAWBEPENBEPUNBERAT
  BERAYBERESBERETBERGSBERGYBERMSBERNEBERRIBERRYBERTHBERYLBESANBESASBESEEBESETBESIN
  BESITBESOMBESOTBESPYBESRABESTSBETAGBETASBETELBETHSBETISBETSOBETTYBEVELBEVERBEVUE
  BEVYSBEWETBEWIGBEZELBEZZIBEZZOBHALUBHANGBHARABHATSBHAVABHOYSBHUTSBIABOBIASSBIBBS
  BIBISBICESBICHYBICKSBIDARBIDDYBIDERBIDESBIDETBIDRIBIELDBIENSBIERSBIFERBIFFSBIFID
  BIGASBIGGSBIGHABIGHTBIGOTBIJASBIJOUBIKESBIKHSBILBOBILBYBILCHBILESBILGEBILGYBILIC
  BILIOBILKSBILLABILLSBILLYBILOSBILSHBINALBINDSBINESBINGEBINGOBINGSBINGYBINHSBINKS
  BINNABINOSBINTSBIODSBIOMEBIONSBIOSEBIOSSBIOTABIPEDBIPODBIRCHBIRDSBIRDYBIRISBIRKS
  BIRLEBIRLSBIRMABIRNSBIRNYBIRRSBIRSEBIRSYBIRTHBISONBISTIBITCHBITERBITESBITISBITOS
  BITTSBITTYBIUNEBIWASBIXINBIZETBIZZSBLABSBLACKBLADEBLADSBLADYBLAESBLAFFBLAHSBLAIN
  BLAIRBLAKEBLAMEBLANCBLANDBLANKBLANSBLAREBLARTBLASEBLASHBLASSBLASTBLATEBLATSBLAWS
  BLAYSBLAZEBLAZYBLEAKBLEARBLEATBLEBSBLECKBLEDSBLEEDBLEESBLENDBLENTBLEOSBLESSBLEST
  BLETSBLIBEBLICKBLIMPBLIMYBLINDBLINKBLIPSBLISSBLITEBLITZBLIZZBLOATBLOBSBLOCKBLOCS
  BLOKEBLOODBLOOMBLOOPBLOREBLOTSBLOUTBLOWNBLOWSBLOWYBLUBSBLUERBLUESBLUETBLUEYBLUFF
  BLUNKBLUNTBLUPSBLURBBLURSBLURTBLUSHBLYPEBOARDBOARSBOASTBOATSBOBACBOBASBOBBYBOBOS
  BOCALBOCCABOCCEBOCESBOCKSBOCOYBODENBODERBODESBODGEBODHIBODLEBODYSBOGANBOGASBOGEY
  BOGGYBOGIEBOGLEBOGOSBOGUEBOGUMBOGUSBOGYSBOHEABOHORBOHOSBOIDSBOILSBOILYBOISTBOJOS
  BOKESBOKOMBOLARBOLASBOLDOBOLDSBOLEDBOLESBOLISBOLKSBOLLSBOLLYBOLOSBOLTIBOLTSBOLUS
  BOMASBOMBOBOMBSBONCEBONDSBONEDBONERBONESBONGOBONGSBONKSBONNYBONUSBONYSBONZEBOOBS
  BOOBYBOODSBOODYBOOFSBOOKSBOOKYBOOLSBOOLYBOOMSBOOMYBOONKBOONSBOORSBOORTBOOSEBOOST
  BOOSYBOOTHBOOTSBOOTYBOOZEBOOZYBORAKBORALBORASBORAXBORDSBOREEBORERBORESBORGHBORGS
  BORHSBORICBORNEBORNSBORONBOROSBORTSBORTYBORTZBORYLBOSCHBOSERBOSESBOSHSBOSKSBOSKY
  BOSNSBOSOMBOSSSBOSSYBOSUNBOTASBOTCHBOTESBOTHSBOTHYBOTTSBOUDSBOUGEBOUGHBOUKSBOULE
  BOUNDBOUNSBOURDBOURGBOURNBOUSEBOUSYBOUTOBOUTSBOUWSBOVIDBOWEDBOWELBOWERBOWETBOWIE
  BOWKSBOWLABOWLSBOWLYBOXENBOXERBOXTYBOXYSBOYARBOYERBOYLABOZALBOZASBOZOSBOZZEBRABS
  BRACABRACEBRACHBRACKBRACTBRADSBRAESBRAGSBRAIDBRAILBRAINBRAKEBRAKYBRANDBRANKBRANS
  BRANTBRASHBRASSBRATSBRAVEBRAVOBRAWLBRAWNBRAWSBRAXYBRAYSBRAZABRAZEBREADBREAKBREAM
  BREBABRECKBREDEBREDIBREDSBREEDBREEKBREESBREISBREMEBRENTBRETHBRETSBRETTBREVABREVE
  BREWSBREYSBRIARBRIBEBRICKBRIDEBRIEFBRIERBRIGSBRILLBRIMSBRINEBRINGBRINKBRINSBRINY
  BRISKBRISSBRITHBRITSBRIZZBROADBROBSBROCHBROCKBRODSBROGSBROILBROKEBROLLBROMABROME
  BRONCBRONKBROODBROOKBROOLBROOMBROONBROOSBROSEBROSYBROTHBROTSBROWNBROWSBRUGHBRUIN
  BRUITBRUKEBRUMEBRUNTBRUSHBRUTEBRUTSBRUZZBUALSBUAZEBUBALBUBASBUBBYBUBOSBUCCABUCHU
  BUCKOBUCKSBUCKYBUDASBUDDYBUDGEBUFFSBUFFYBUFOSBUGANBUGGYBUGLEBUGREBUHLSBUHRSBUILD
  BUILTBUISTBUKHSBULAKBULBSBULBYBULGEBULGYBULKSBULKYBULLABULLSBULLYBULSEBULTSBUMBO
  BUMPSBUMPYBUNASBUNCEBUNCHBUNDSBUNDYBUNGOBUNGSBUNGYBUNKOBUNKSBUNNYBUNTSBUNTYBUNYA
  BUOYSBURANBURAOBURDSBURELBURESBURETBURGHBURGSBURINBURISBURKABURKEBURLSBURLYBURNS
  BURNTBURNYBUROSBURPSBURROBURRSBURRYBURSABURSEBURSTBURTSBURYSBUSBYBUSHIBUSHSBUSHY
  BUSKSBUSKYBUSSSBUSSUBUSTSBUSYSBUTCHBUTICBUTTEBUTTSBUTTYBUTYLBUTYRBUXOMBUYERBUZZS
  BUZZYBYEESBYGOSBYLAWBYONSBYOUSBYRESBYSENBYTHSBYWAYCAAMACAAMSCABALCABANCABASCABBY
  CABDACABERCABINCABIOCABLECABOBCABOTCACAMCACAOCACHECACKSCACTICACURCADDYCADERCADES
  CADETCADEWCADGECADGYCADISCADOSCADRECADUACADUSCAECACAFFACAFHSCAFIZCAGEDCAGERCAGES
  CAGEYCAGGYCAGITCAHIZCAHOTCAHOWCAIDSCAINSCAIRDCAIRNCAJUNCAKERCAKESCAKEYCAKYSCALFS
  CALIDCALIXCALKSCALLICALLOCALLSCALMSCALMYCALORCALPSCALVECALXSCALYXCAMANCAMBSCAMEL
  CAMEOCAMESCAMPOCAMPSCAMUSCANALCANCHCANDSCANDYCANELCANERCANESCANIDCANKSCANNACANNY
  CANOECANONCANSOCANTOCANTSCANTYCANUNCANYSCAOBACAPAXCAPEDCAPELCAPERCAPESCAPHSCAPON
  CAPOTCAPPYCAPSACARATCARBOCARDOCARDSCARERCARESCARETCARGACARGOCARIDCARKSCARLSCAROA
  CAROBCAROLCAROMCARPSCARRSCARRYCARSECARTECARTSCARTYCARUACARVECARYLCASALCASCOCASED
  CASERCASESCASHACASHSCASKSCASSECASSSCASTECASTSCATANCATCHCATERCATESCATTYCAUCHCAUDA
  CAUKSCAULDCAULSCAUMACAUMSCAUPOCAUPSCAUSECAVAECAVALCAVASCAVELCAVESCAVIECAVILCAVUS
  CAVYSCAWKSCAWKYCAXONCAZASCEASECEBIDCEBILCEBURCEDARCEDERCEDESCEDRECEDRYCEIBOCEILE
  CEILSCELLACELLOCELLSCELTSCENSECENTOCENTSCEORLCEPASCEPESCEPSSCEQUICERALCERASCERCI
  CEREDCERERCERESCERIACERICCERINCERNSCEROSCERTYCERYLCESSSCESTSCETICCETINCETISCETYL
  CHAASCHABSCHACKCHADSCHAFECHAFFCHAFTCHAINCHAIRCHAISCHAJACHAKACHALKCHALSCHAMPCHAMS
  CHANGCHANKCHANTCHAOSCHAPECHAPSCHAPTCHARDCHARECHARKCHARMCHARRCHARSCHARTCHARYCHASE
  CHASMCHATICHATSCHAUKCHAUSCHAWKCHAWLCHAWSCHAYACHAYSCHEAPCHEATCHECKCHEEKCHEEPCHEER
  CHEESCHEETCHEFSCHEIRCHEKECHEKICHELACHELPCHENACHENGCHERTCHESSCHESTCHETHCHEVECHEVY
  CHEWSCHEWYCHIASCHICKCHICOCHICSCHIDECHIDSCHIEFCHIENCHIHSCHILDCHILECHILICHILLCHILS
  CHIMECHINACHINECHINGCHINKCHINOCHINSCHINTCHIPSCHIRKCHIRMCHIROCHIRPCHIRRCHITSCHIVE
  CHLORCHOBSCHOCACHOCKCHOELCHOGACHOILCHOIRCHOKECHOKYCHOLACHOLDCHOLICHOLSCHOMPCHOOP
  CHOPACHOPSCHORDCHORECHORTCHOSECHOTTCHOUPCHOUSCHOWKCHOWSCHOYACHRIACHUBSCHUCKCHUFA
  CHUFFCHUGSCHUMPCHUMSCHUNKCHUNSCHURLCHURMCHURNCHURRCHUTECHUTSCHYAKCHYLECHYMECIBOL
  CICADCICERCIDERCIGARCIGUACILIACIMEXCINCHCINCTCINELCINESCIONSCIPOSCIRCACIRRICISCO
  CISESCISTACISTSCITEECITERCITESCITUACITYSCIVESCIVETCIVICCIVILCIVVYCLACKCLADSCLAGS
  CLAIMCLAMBCLAMECLAMPCLAMSCLANGCLANKCLANSCLAPSCLAPTCLARKCLAROCLARTCLARYCLASHCLASP
  CLASSCLATSCLAUTCLAVACLAVECLAVYCLAWKCLAWSCLAYSCLEADCLEAMCLEANCLEARCLEATCLECKCLEDS
  CLEEKCLEESCLEFSCLEFTCLEGSCLEMSCLEPSCLERKCLEVECLEWSCLICKCLIFFCLIFTCLIMACLIMBCLIME
  CLINECLINGCLINKCLINTCLIPSCLIPTCLITECLITSCLIVECLOAKCLOAMCLOCKCLODSCLOFFCLOGSCLOIT
  CLOMBCLONECLOOFCLOOPCLOOTCLOPSCLOSECLOSHCLOTECLOTHCLOTSCLOUDCLOURCLOUTCLOVECLOWN
  CLOWSCLOYSCLUBSCLUCKCLUESCLUFFCLUMPCLUNGCLUNKCLYERCLYPECNIDACOACHCOACTCOAIDCOAKS
  COALSCOALYCOAPTCOARBCOASTCOATICOATSCOAXSCOAXYCOBBYCOBIACOBLECOBRACOCASCOCCICOCCO
  COCKSCOCKYCOCOACOCOSCODASCODERCODESCODEXCODOLCODONCODOSCOEDSCOFFSCOFTSCOGONCOGUE
  COHOLCOHOSCOIFSCOIGNCOILSCOINSCOINYCOIRSCOKERCOKESCOKYSCOLASCOLDSCOLESCOLICCOLIN
  COLISCOLKSCOLLSCOLLYCOLONCOLORCOLPSCOLTSCOLYSCOLZACOMALCOMASCOMBSCOMBYCOMERCOMES
  COMETCOMFYCOMICCOMMACOMPOCONALCONCHCONDSCONEDCONERCONESCONGACONICCONINCONKSCONKY
  CONNSCONTECONTOCONUSCONYSCOOBACOOEECOOERCOOFSCOOJACOOKSCOOKYCOOLSCOOLYCOOMBCOOMS
  COOMYCOONSCOONYCOOPSCOOSTCOOTSCOPALCOPASCOPEICOPENCOPERCOPESCOPISCOPPYCOPRACOPRS
  COPSECOPSYCOPUSCOPYSCOQUECORAHCORALCORAMCORASCORDSCORDYCOREDCORERCORESCORFSCORGE
  CORGICORKECORKSCORKYCORMSCORNSCORNUCORNYCOROACOROLCORPSCORSECORTACORYLCOSECCOSET
  COSHSCOSSECOSSSCOSTACOSTSCOSYSCOTCHCOTESCOTHECOTHSCOTHYCOTOSCOTTACOTTECOTTYCOUAC
  COUCHCOUDECOUESCOUGHCOULDCOULSCOUMACOUNTCOUPECOUPSCOURBCOURTCOUTHCOVEDCOVERCOVES
  COVETCOVEYCOVIDCOVINCOWALCOWERCOWLECOWLSCOWYSCOXALCOXASCOXYSCOYANCOYLYCOYOLCOYOS
  COYPUCOZENCOZESCOZYSCRABSCRACKCRAFTCRAGSCRAINCRAKECRAMPCRAMSCRANECRANKCRANSCRAPE
  CRAPSCRAPYCRARECRASHCRASSCRATECRAVECRAVOCRAWLCRAWMCRAWSCRAZECRAZYCREAKCREAMCREAS
  CREATCREEDCREEKCREELCREEMCREENCREEPCREESCRENACREPECREPTCREPYCRESSCRESTCRETACREWS
  CRIBOCRIBSCRICKCRICSCRIEDCRIERCRIEYCRIGSCRILECRIMECRIMPCRINECRINKCRINSCRISPCRISS
  CRITHCROAKCROCICROCKCROCSCROFTCROMECRONECRONKCRONYCROODCROOKCROOLCROONCROPSCRORE
  CROSACROSSCROUPCROUTCROWDCROWLCROWNCROWSCROYSCROZECRUCECRUCKCRUDECRUELCRUETCRUMB
  CRUMPCRUMSCRUNKCRUNTCRUORCRUSECRUSHCRUSSCRUSTCRUTHCRUXSCRYPTCTENECUBBYCUBEBCUBER
  CUBESCUBICCUBISCUBITCUCKSCUDDYCUECACUFFSCUFFYCUIRSCUKESCULETCULLACULLSCULLYCULMS
  CULMYCULPACULTSCUMALCUMAYCUMBUCUMICCUMINCUMOLCUMPSCUMYLCUNYECUPAYCUPELCUPPYCURBS
  CURBYCURCHCURDSCURDYCURERCURESCURIECURINCURIOCURLSCURLYCURNSCURRSCURRYCURSECURST
  CURTSCURUACURVECURVYCUSECCUSHSCUSHYCUSIECUSKSCUSPSCUSSOCUSSSCUTCHCUTESCUTIECUTIN
  CUTISCUTTYCUTUPCUVYSCUYASCYANSCYATHCYCADCYCLECYKESCYLIXCYMARCYMASCYMBACYMESCYNIC
  CYPRECYRUSCYSTSCYTONCZARSDABBADABBSDABBYDACESDADAPDADASDADDYDADESDADOSDAERSDAFFS
  DAFFYDAFTSDAGGADAGGYDAGSSDAILYDAINSDAIRADAIRIDAIRYDAISSDAISYDAIVADAKERDAKIRDALAR
  DALERDALESDALISDALKSDALLEDALLYDALTSDAMANDAMASDAMESDAMIEDAMMEDAMNSDAMPSDAMPYDANCE
  DANDADANDSDANDYDANGSDANIODANKSDANLIDANTADARACDARAFDARATDARBYDARERDARESDARGSDARIC
  DARISDARKSDARKYDARNSDAROODARRSDARSTDARTSDASHSDASHYDASISDASNTDASSYDATASDATCHDATER
  DATESDATILDATUMDAUBEDAUBSDAUBYDAUDSDAUNTDAUTSDAUWSDAVENDAVERDAVITDAVYSDAWDYDAWNS
  DAWNYDAWUTDAYALDAYSSDAZEDDAZESDAZYSDEADSDEAFSDEAIRDEALSDEALTDEANSDEARSDEARYDEASH
  DEATHDEAVEDEBARDEBBYDEBENDEBITDEBTSDEBUSDEBUTDECADDECALDECANDECAPDECAYDECILDECKE
  DECKSDECOYDECRYDECUSDECYLDEDOSDEEDSDEEDYDEEMSDEEPSDEERSDEFATDEFERDEFOGDEFTSDEFYS
  DEGASDEGUMDEGUSDEICEDEIFYDEIGNDEINKDEISMDEISTDEITYDEKKODEKLEDELAYDELESDELFSDELFT
  DELLSDELTADELVEDEMALDEMESDEMISDEMITDEMOBDEMONDEMOSDEMYSDENATDENDADENESDENIMDENSE
  DENTSDENTYDENYSDEOTADEPASDEPOHDEPOTDEPTHDERAHDERATDERAYDERBYDERESDERICDERMADERMS
  DERNSDERRYDESEXDESISDESKSDESMADESSADESSSDESYLDETARDETAXDETERDETINDETURDEUCEDEULS
  DEVASDEVILDEVOWDEWANDEWAXDEWERDEWYSDHABBDHAISDHAKSDHANSDHAVADHAWSDHERIDHOBIDHOLE
  DHONIDHOONDHOTIDHOULDHOWSDHYALDIACTDIALSDIAMBDIANSDIARYDIBSSDICERDICESDICHSDICKS
  DICKYDICOTDICTADIDDYDIDIEDIDLEDIDNADIDNTDIDSTDIDYMDIEBSDIEMSDIENEDIERSDIETSDIGHT
  DIGITDIGSSDIKASDIKERDIKESDILDODILLIDILLSDILLYDILOSDIMERDIMESDIMITDIMLYDIMPSDINAR
  DINERDINESDINGEDINGODINGSDINGYDINICDINKSDINKYDINTSDINUSDIODEDIOLSDIOSEDIOTADIOXY
  DIRDSDIRESDIRGEDIRKSDIRLSDIRTSDIRTYDISCSDISHSDISKSDISMEDISNADISSSDITALDITASDITCH
  DITERDITESDITTODITTYDIVANDIVASDIVELDIVERDIVESDIVOTDIVUSDIVVYDIXIEDIXITDIXYSDIZEN
  DIZZYDJAVEDOABSDOATSDOBBYDOBESDOBLADOBRADOBYSDOCKSDODDSDODDYDODGEDODGYDODOSDOERS
  DOESSDOESTDOFFSDOGALDOGESDOGGODOGGYDOGIEDOGLYDOGMADOGSSDOGYSDOIGTDOILYDOINADOING
  DOITSDOKESDOLASDOLESDOLIADOLISDOLLSDOLLYDOLORDOLTSDOMALDOMBADOMERDOMESDOMICDOMNS
  DOMPTDOMYSDONAXDONEEDONESDONEYDONGADONGSDONNADONORDONTSDONUMDOOBSDOOJADOOKSDOOLI
  DOOLSDOOLYDOOMSDOONSDOORSDOPASDOPERDOPESDOPEYDORABDORADDOREEDORIADORJEDORMSDORMY
  DORNSDORPSDORTSDORTYDORYSDOSASDOSERDOSESDOSISDOSSSDOTALDOTEDDOTERDOTESDOTTYDOTYS
  DOUARDOUBTDOUCEDOUCSDOUGHDOUMSDOUPSDOURSDOUSEDOUTSDOVERDOVESDOWDSDOWDYDOWEDDOWEL
  DOWERDOWFSDOWIEDOWLSDOWNSDOWNYDOWPSDOWRYDOWSEDOXASDOXYSDOZEDDOZENDOZERDOZESDOZYS
  DRABSDRAFFDRAFTDRAGODRAGSDRAILDRAINDRAKEDRAMADRAMMDRAMSDRANGDRANKDRANTDRAPEDRATE
  DRATSDRAWKDRAWLDRAWNDRAWSDRAYSDREADDREAMDREARDREEPDREESDREGSDRENGDRESSDRESTDREWS
  DRIASDRIBSDRIEDDRIERDRIFTDRILLDRINKDRINNDRIPSDRISKDRIVEDROGHDROITDROLLDROMEDRONA
  DRONEDRONYDROOLDROOPDROPSDROPTDROSSDROUDDROUKDROVEDROVYDROWNDROWSDRUBSDRUGSDRUID
  DRUMSDRUNGDRUNKDRUPEDRUSEDRUSYDRUXYDRYADDRYASDRYLYDRYTHDUADSDUALIDUALSDUBBADUBBS
  DUBBYDUBSSDUCALDUCATDUCESDUCHYDUCKSDUCTSDUDESDUELSDUERSDUETSDUFFSDUGALDUHATDUIMS
  DUITSDUJANDUKESDUKHNDULERDULIADULLSDULLYDULSEDULTSDULYSDUMASDUMBADUMBSDUMMYDUMPS
  DUMPYDUNALDUNCEDUNCHDUNESDUNGSDUNGYDUNKSDUNNEDUNNYDUNSTDUNTSDUNYSDUOLEDUPERDUPES
  DUPLADUPLEDUPPYDURALDURASDURAXDURESDURNSDUROSDURRADURRYDURSTDURYLDUSHSDUSIODUSKS
  DUSKYDUSTSDUSTYDUTCHDUTRADUTYSDUVETDWALEDWALMDWANGDWARFDWELLDWELTDWINEDYADSDYCES
  DYERSDYINGDYKERDYKESDYNESEACHSEAGEREAGLEEAGREEAREDEARLSEARLYEARNSEARTHEASELEASER
  EASESEASTSEASYSEATENEATEREATSSEAVEDEAVEREAVESEBOESEBONSEBONYECADSECHEAECHESECHOS
  ECIZEECLATECOIDECOLEECRUSECTADECTALEDDEREDDOSEDDYSEDEASEDEMAEDGEDEDGEREDGESEDGYS
  EDICTEDIFYEDITSEDUCEEDUCTEELEREELYSEERIEEGADSEGESTEGGEREGGYSEGMASEGOLSEGRETEHEUS
  EIDEREIGHTEIGNEEIMEREJECTEJOOSEKAHAEKERSEKINGEKKASELAINELANDELATEELBOWELDERELDIN
  ELECTELEGYELEMIELFICELFINELIDEELITEELLESELMYSELODSELOGEELOPEELOPSELSESELSINELUDE
  ELUTEELVANELVERELVESELVETEMBAREMBAYEMBEDEMBEREMBOGEMBOWEMBOXEMBUSEMCEEEMEEREMEND
  EMERYEMIRSEMITSEMMASEMMEREMMETEMOTEEMPTSEMPTYEMYDSENACTENAGEENAMSENAPTENARMENATE
  ENCUPENDEDENDERENDEWENDOWENDUEENEMAENEMYENGEMENHATENIACENJOYENNUIENOILENOLSENORM
  ENOWSENRAYENRIBENROLENRUTENSESENSKYENSUEENTADENTALENTERENTIAENTRYENUREENVOYENVYS
  ENZYMEOANSEOSINEPACTEPEESEPHAHEPHASEPHODEPHOREPICSEPOCHEPODEEPOPTEPOSSEPULOEQUAL
  EQUIDEQUIPERADEERALSERASEERBIAERECTEREPTERGALERGONERGOTERIASERICSERIKAERIZOERNES
  ERODEEROSEEROSSERRORERTHSERUCAERUCSERUCTERUPTESCASESEREESHINESKERESNESESPYSESSAY
  ESSEDESTERESTOCESTOPESTREESTUSETCHSETHALETHELETHERETHICETHIDETHOSETHYLETNASETTLE
  ETUASETUDEETUISETYMSEUGESEUPADEUSOLEVADEEVASEEVENSEVENTEVERSEVERTEVERYEVICTEVILS
  EVOESEVOKEEWDEREWERSEWERYEWRYSEXACTEXALTEXAMSEXCELEXDIEEXEATEXERTEXESSEXILEEXIST
  EXITEEXITSEXLEXEXODEEXODYEXONSEXPELEXTEREXTOLEXTRAEXUDEEXULTEYAHSEYASSEYEDSEYENS
  EYERSEYEYSEYINGEYNESEYOTSEYOTYEYRASEYRESEYRIEEYRIREZBASFABESFABLEFACEDFACERFACES
  FACETFACIAFACKSFACTSFACTYFACYSFADDYFADEDFADENFADERFADESFADGEFADYSFAERYFAFFSFAFFY
  FAGERFAGESFAGOTFAHAMFAILSFAINSFAINTFAIRMFAIRSFAIRYFAITHFAKERFAKESFAKIRFAKYSFALLS
  FALLYFALSEFALXSFAMESFANALFANAMFANASFANCYFANDSFANGSFANGYFANONFANTSFAONSFARADFARCE
  FARCYFARDEFARDHFARDOFARERFARESFARLSFARMSFARMYFAROSFARSEFASHSFASSSFASTSFATALFATED
  FATESFATILFATLYFATTYFATWAFAUGHFAULDFAULTFAUNSFAUSEFAUSTFAUVEFAVNSFAVORFAVUSFAWNS
  FAWNYFAZESFEAKSFEALSFEARSFEASTFEATSFEATYFEAZEFECALFECESFECKSFEEDSFEEDYFEELSFEERE
  FEERSFEEZEFEIFSFEIGNFEILSFEINTFEISSFEISTFELIDFELLSFELLYFELONFELSSFELTSFELTYFEMES
  FEMICFEMURFENCEFENDSFENDYFENKSFENNYFENTSFEODSFEOFFFERALFERIAFERIEFERKSFERLYFERME
  FERNSFERNYFERRIFERRYFERUSFESSSFESTSFETALFETCHFETIDFETORFETUSFEUARFEUDSFEUEDFEVER
  FEZZYFIARDFIARSFIATSFIBERFIBRYFICESFICHEFICHUFICOSFIDESFIDGEFIELDFIENDFIENTFIERY
  FIFERFIFESFIFIEFIFOSFIFTHFIFTYFIGGYFIGHTFIKESFIKIEFILAOFILARFILCHFILERFILESFILET
  FILLSFILLYFILMSFILMYFILOSFILSSFILTHFINALFINCHFINDSFINERFINESFINISFINKSFINNYFIORD
  FIQUEFIRCAFIREDFIRERFIRESFIRKSFIRMSFIRNSFIRRYFIRSTFIRTHFISCSFISESFISHSFISHYFISTS
  FISTYFITCHFITLYFITTYFIVERFIVESFIXEDFIXERFIZZSFIZZYFJELDFLACKFLAFFFLAGSFLAILFLAIR
  FLAKEFLAKSFLAKYFLAMBFLAMEFLAMSFLAMYFLANEFLANKFLANSFLAPSFLAREFLARYFLASHFLASKFLATS
  FLAVOFLAWNFLAWSFLAWYFLAXSFLAXYFLAYSFLEAMFLEASFLEAYFLECKFLEDSFLEERFLEESFLEETFLESH
  FLETSFLEWSFLEXSFLEYSFLICKFLIERFLIMPFLINGFLINTFLIPEFLIPSFLIRTFLISKFLITEFLITSFLIXS
  FLOATFLOBSFLOCKFLOCSFLOESFLOEYFLOGSFLONGFLOODFLOORFLOPSFLORAFLORYFLOSHFLOSSFLOTA
  FLOTSFLOURFLOUTFLOWNFLOWSFLUBSFLUEDFLUERFLUESFLUEYFLUFFFLUIDFLUKEFLUKYFLUMEFLUMP
  FLUNGFLUNKFLUORFLURNFLURRFLUSHFLUSKFLUTEFLUTYFLUXSFLYERFLYPEFOALSFOALYFOAMSFOAMY
  FOCALFOCISFOCUSFODDAFODERFODGEFOEHNFOGEYFOGGYFOGLEFOGONFOGOSFOGOUFOGUSFOGYSFOHAT
  FOILSFOISTFOLDSFOLDYFOLESFOLIAFOLIEFOLIOFOLKSFOLKYFOLLYFOMESFONDSFONDUFONLYFONOS
  FONSSFONTSFOODSFOODYFOOLSFOOTSFOOTYFOPPYFORASFORAYFORBSFORBYFORCEFORDOFORDSFORDY
  FORELFORESFORGEFORGOFORKSFORKYFORMEFORMSFORMYFORTEFORTHFORTSFORTYFORUMFOSHSFOSIE
  FOSSAFOSSEFOTCHFOTUIFOUDSFOULSFOUNDFOUNSFOUNTFOURSFOUTEFOUTHFOVEAFOWKSFOWLSFOXER
  FOXYSFOYERFOZYSFRABSFRACKFRAESFRAIDFRAIKFRAILFRAMEFRANCFRANKFRAPSFRASEFRASSFRATS
  FRAUDFRAWNFRAYNFRAYSFRAZEFREAKFREAMFRECKFREEDFREERFREESFREETFREIRFREITFREMDFRESH
  FRETSFRETTFRIARFRIBSFRIEDFRIERFRIGSFRIKEFRILLFRIMSFRISKFRISTFRITHFRITSFRITTFRIZE
  FRIZSFRIZZFROCKFROESFROGSFROMSFRONDFRONTFROOMFROREFRORYFROSHFROSTFROTHFROTSFROWL
  FROWNFROWSFROWYFROZEFRUITFRUMPFRUSHFRYERFUBBYFUBSYFUCISFUCUSFUDERFUDGEFUDGYFUELS
  FUFFSFUFFYFUGALFUGGYFUGLEFUGUEFUGUSFUJISFULKSFULLSFULLYFULTHFULWAFUMERFUMESFUMET
  FUMYSFUNDIFUNDSFUNGIFUNGOFUNISFUNKSFUNKYFUNNYFUNTSFURALFURANFURCAFURILFURLSFUROR
  FURRYFURYLFURYSFURZEFURZYFUSCSFUSEDFUSEEFUSESFUSHTFUSILFUSSSFUSSYFUSTSFUSTYFUTES
  FUTWAFUYESFUZESFUZZSFUZZYFYKESFYRDSGABBYGABISGABLEGABYSGADDIGADESGADGEGADIDGAENS
  GAETSGAFFEGAFFSGAGEEGAGERGAGESGAGORGAILYGAINEGAINSGAIRSGAITSGAIZEGALAHGALASGALEA
  GALEEGALESGALETGALEYGALISGALLAGALLSGALLYGALOPGALPSGALTSGAMBAGAMBSGAMESGAMICGAMIN
  GAMMAGAMMYGAMPSGAMUTGAMYSGANAMGANCHGANEFGANESGANGAGANGEGANGSGANJAGANSYGANTAGANTS
  GANZAGAOLSGAPASGAPERGAPESGAPOSGAPPYGAPYSGARADGARASGARBSGARCEGARDYGAREHGARESGARLE
  GARNSGAROOGARSEGARTHGARUMGASHSGASHYGASPSGASPYGASSYGASTSGATASGATCHGATEDGATERGATES
  GATORGAUBSGAUBYGAUDSGAUDYGAUGEGAULTGAUMSGAUMYGAUNSGAUNTGAUPSGAURSGAUSSGAUTSGAUZE
  GAUZYGAVELGAVESGAWBYGAWKSGAWKYGAWMSGAWNSGAYALGAZEEGAZELGAZERGAZESGAZISGAZONGAZYS
  GEALSGEANSGEARSGEASEGEATSGEBURGECKOGECKSGEEKSGEESEGEESTGEETSGEGGSGEINSGEIRAGELDS
  GELIDGELLSGELLYGELTSGEMELGEMMAGEMMYGEMOTGEMULGENALGENASGENEPGENESGENETGENICGENIE
  GENIIGENINGENIPGENOMGENOSGENREGENROGENSSGENTSGENTYGENUAGENUSGENYSGEODEGEOIDGEOTY
  GERAHGERBEGERBSGERIMGERIPGERMSGERMYGERSSGESSOGESTEGESTSGETAHGETASGETUPGEUMSGEYAN
  GHATSGHAZIGHEESGHOOMGHOSTGHOULGIANTGIBBYGIBELGIBERGIBESGIBUSGIDDYGIEDSGIENSGIFTS
  GIGOTGILDSGILIAGILIMGILLSGILLYGILOSGILPYGILSEGILTSGIMELGIMPSGINGSGINKSGINNYGIPON
  GIRBAGIRDSGIRLSGIRLYGIRNSGIRNYGIROSGIRRSGIRSEGIRSHGIRTHGIRTSGISHSGISLAGISTSGITHS
  GIVENGIVERGIVESGIVEYGIZZSGLACEGLACKGLADEGLADSGLADYGLAGAGLAIKGLAIRGLAKYGLAMSGLAND
  GLANSGLAREGLARSGLARYGLASSGLAUMGLAURGLAZEGLAZYGLEAMGLEANGLEBAGLEBEGLEDEGLEDYGLEED
  GLEEKGLEESGLEETGLEGSGLENSGLENTGLIALGLIASGLIBSGLIDEGLIFFGLIMEGLINKGLINTGLISKGLOAM
  GLOATGLOBEGLOBYGLOEAGLOMEGLOMSGLOOMGLOPSGLOREGLORSGLORYGLOSSGLOSTGLOUTGLOVEGLOWS
  GLOYSGLOZEGLUBSGLUCKGLUEDGLUERGLUESGLUEYGLUGSGLUMAGLUMEGLUMPGLUMSGLUTSGLYPHGNARL
  GNARSGNASHGNATSGNAWNGNAWSGNOMEGOADSGOAFSGOALSGOATSGOATYGOAVEGOBANGOBBEGOBBYGOBIS
  GOBOSGOBYSGODESGODETGODLYGOELSGOERSGOESSGOETYGOFFSGOGGAGOGOSGOINGGOLASGOLDSGOLDY
  GOLEEGOLEMGOLFSGOLISGOLLYGOLOEGOLPEGOMERGONADGONALGONERGONESGONGSGONIAGONIDGONNE
  GONYSGOODSGOODYGOOFSGOOFYGOOKSGOOLSGOOMAGOONSGOOSEGOOSYGORALGORANGORASGORBSGORCE
  GORERGORESGORGEGORICGORRAGORRYGORSEGORSYGORYSGOSHSGOSSYGOTCHGOTESGOTRAGOUGEGOUMI
  GOUPSGOURDGOUTSGOUTYGOVESGOWANGOWFSGOWKSGOWLSGOWNSGOYIMGOYINGOYLEGRABSGRACEGRADE
  GRADSGRAFFGRAFTGRAILGRAINGRAIPGRAMAGRAMEGRAMPGRAMSGRANDGRANEGRANKGRANOGRANTGRAPE
  GRAPHGRAPYGRASPGRASSGRATEGRATSGRAVEGRAVYGRAYSGRAZEGREATGREBEGRECEGREEDGREENGREES
  GREETGREGEGREGOGREINGREWSGREYSGRICEGRIDEGRIDSGRIEFGRIFFGRIFTGRIGSGRIKEGRILLGRIME
  GRIMPGRIMSGRIMYGRINDGRINSGRIPEGRIPSGRIPYGRISSGRISTGRITHGRITSGROANGROATGROFFGROGS
  GROINGROOMGROOPGROOTGROPEGROSSGROSZGROTSGROUFGROUPGROUTGROVEGROVYGROWLGROWNGROWS
  GRUBSGRUELGRUESGRUFFGRUMEGRUMPGRUMSGRUNSGRUNTGRUSHGRUSSGRYDEGUABAGUACOGUAKAGUAMA
  GUANAGUANOGUANSGUAOSGUARAGUARDGUARSGUASAGUAVAGUAZAGUBBOGUCKIGUDESGUDGEGUDOKGUESS
  GUESTGUFASGUFFSGUFFYGUGALGUGUSGUHRSGUIBAGUIBSGUIDEGUIGEGUIJOGUILDGUILEGUILTGUILY
  GUISEGULAEGULARGULASGULCHGULESGULFSGULFYGULIXGULLSGULLYGULPSGULPYGUMBOGUMBYGUMLY
  GUMMAGUMMYGUMPSGUNASGUNDIGUNDYGUNGEGUNJSGUNKSGUNLSGUNNEGUNNYGUPPYGURGEGURKSGURLS
  GURLYGURRSGURRYGURTSGURUSGUSHSGUSHYGUSLAGUSLEGUSSSGUSTOGUSTSGUSTYGUTTAGUTTEGUTTI
  GUTTSGUTTYGUYERGUZESGWAGSGWEEDGWELYGWINEGYLESGYMELGYNESGYNICGYPESGYPSSGYPSYGYRAL
  GYRESGYRICGYRISGYRONGYROSGYRUSGYTESGYVESHAABSHAAFSHABITHABUSHACHEHACKSHACKYHADDO
  HADESHADJIHADJSHAECSHAEMSHAETSHAFFSHAFIZHAFTSHAGGYHAGIAHAGISHAIKSHAILSHAILYHAINE
  HAINSHAIREHAIRSHAIRYHAJESHAJIBHAKAMHAKESHAKIMHAKOSHAKUSHALALHALASHALCHHALERHALES
  HALFSHALLSHALMAHALOSHALSEHALSSHALTSHALVEHAMALHAMELHAMESHAMISHAMMYHAMSAHAMUSHAMZA
  HANCEHANCHHANDSHANDYHANGEHANIFHANKSHANKYHANNAHANSAHANSEHANTSHAOLEHAOMAHAORIHAPLY
  HAPPYHAPUSHARBIHARDSHARDYHAREMHARESHARKAHARKSHARLSHARMSHARNSHARPSHARRSHARRYHARSH
  HARTSHASANHASHSHASHYHASKSHASKYHASPSHASTAHASTEHASTYHATCHHATERHATESHATHIHATHSHATTS
  HATTYHAUGHHAULDHAULMHAULSHAUNTHAUSEHAVELHAVENHAVERHAVESHAVOCHAWERHAWKSHAWKYHAWMS
  HAWOKHAWSEHAYASHAYEYHAYZSHAZELHAZENHAZERHAZESHAZLEHAZYSHEADSHEADYHEAFSHEALDHEALS
  HEAPSHEAPYHEARSHEARTHEATHHEATSHEAVEHEAVYHECHSHECKSHECTEHEDERHEDGEHEDGYHEEDSHEEDY
  HEELSHEERSHEEZEHEEZYHEFTSHEFTYHEIAUHEIGHHEIISHEIRSHELESHELIOHELIXHELLOHELLSHELLY
  HELMSHELOEHELPSHELVEHEMADHEMALHEMENHEMESHEMICHEMINHEMLSHEMOLHEMPSHEMPYHENADHENCE
  HENDSHENNAHENNYHENRYHENTSHEPARHERBSHERBYHERDSHEREMHERESHERLSHERMAHERNEHERNSHERON
  HEROSHERSEHERSSHERTZHESTSHEUAUHEUGHHEVISHEWELHEWERHEWNSHEWTSHEXADHEXASHEXERHEXIS
  HEXYLHIANTHIATEHICKSHIDEDHIDERHIDESHIELDHIGHSHIGHTHIKERHIKESHILCHHILLSHILLYHILSA
  HILTSHILUMHILUSHIMPSHINAUHINCHHINDSHINGEHINGSHINNYHINTSHIPERHIPESHIPPOHIPPYHIRED
  HIRERHIRESHIROSHIRSEHISHSHISNSHISSSHISTSHITCHHITHEHIVERHIVESHIZZSHOARDHOARSHOARY
  HOASTHOAXSHOBBYHOBOSHOCCOHOCKSHOCKYHOCUSHODDYHOERSHOGANHOGASHOGGYHOICKHOINSHOISE
  HOISTHOITSHOJUSHOKEYHOKUMHOLDSHOLERHOLESHOLEYHOLIAHOLLAHOLLOHOLLSHOLLYHOLMSHOLTS
  HOLYSHOMERHOMESHOMEYHOMOSHOMYSHONDAHONDOHONESHONEYHONGSHONKSHONORHOOCHHOODSHOOEY
  HOOFSHOOFYHOOKSHOOKYHOOLYHOONSHOOPSHOOSEHOOSHHOOTSHOOVEHOPEDHOPERHOPESHOPISHOPPY
  HORALHORASHORDEHORMEHORNSHORNYHORSEHORSTHORSYHORYSHOSEDHOSELHOSESHOSTSHOTCHHOTEL
  HOTISHOTLYHOUGHHOUNDHOURIHOURSHOUSEHOUSYHOVELHOVENHOVERHOVESHOWDYHOWELHOWESHOWFF
  HOWKSHOWLSHOWSOHOYLEHUACAHUACOHUBBAHUBBSHUBBYHUCHOHUCKSHUEDSHUERSHUFFSHUFFYHUGES
  HUIASHUKESHULASHULKSHULKYHULLSHULUSHUMANHUMBOHUMETHUMICHUMIDHUMINHUMORHUMPHHUMPS
  HUMPYHUMUSHUNCHHUNDIHUNGSHUNHSHUNKSHUNKYHUNTSHURASHURDSHURESHURLSHURLYHURONHURRS
  HURRYHURSTHURTSHURTYHUSESHUSHOHUSHSHUSKSHUSKYHUSOSHUSSSHUSSYHUTCHHUTIAHUZZAHUZZS
  HYDROHYENAHYINGHYKESHYLEGHYLESHYLICHYMENHYMNSHYNDEHYNESHYOIDHYPERHYPHAHYPHOHYPOS
  HYRAXHYSONIAMBIIAMBSIBEXSIBIDSIBISSIBOTAICACOICEDSICHORICHOSICHUSICICAICILYICING
  ICONSICTICICTUSIDANTIDDATIDEALIDEASIDESSIDGAHIDICSIDIOMIDIOTIDITEIDLERIDLESIDLYS
  IDOLAIDOLSIDOSEIDRYLIDYLSIFFYSIGLOOIHRAMIIWISIJMASIKATSIKEYSIKONAIKRASILEACILEON
  ILEUMILEUSILEXSILIACILIALILIASILIAUILIMAILIUMILKASILLTHILLYSILOTSIMAGEIMAGOIMAMS
  IMBANIMBATIMBEDIMBERIMBESIMBUEIMIDEIMINEIMINOIMMEWIMMISIMMITIMMIXIMPARIMPELIMPEN
  IMPISIMPLYIMPOTIMPYSIMSHIINAJAINANEINAPTINARMINBESINBYSINCHSINCOGINCURINCUSINCUT
  INDANINDESINDEXINDICINDRIINDUEINDYLINDYSINEPTINERMINERTINFERINFITINFIXINFRAINGLE
  INGOTINIALINIONINKENINKERINKETINKLEINKSSINKYSINLAWINLAYINLETINLYSINNERINNETINOMA
  INONEINORBINPUTINROSINRUBINRUNINSEAINSEEINSETINTERINTILINTOSINTUEINULAINUREINURN
  INWITIODICIODOLIODOSIONICIOTASIPIDSIPILSIRADEIRATEIRENEIRIANIRIDSIRISSIROKOIROKS
  IRONEIRONSIRONYISBASISLAYISLESISLETISLOTISMALISMYSISSEIISSUEISTLEITCHSITCHYITCZE
  ITEMSITEMYITERSITHERITMOSIVIEDIVINSIVORYIWISSIZARDIZARSIZLESIZOTEIZTLEJABIAJABOT
  JABULJACALJACKOJACKSJACUSJADEDJADESJADYSJAGATJAGERJAGGYJAGIRJAGLAJAGUAJAILSJAKES
  JAKOSJALAPJAMANJAMASJAMBOJAMBSJAMISJAMMYJANESJANKSJANNSJANTUJANUAJAOBSJAPANJAPER
  JAPESJARASJARGSJARLSJARRAJARRYJASEYJASSSJATHAJATISJATOSJAUKSJAUNSJAUNTJAUPSJAVER
  JAWABJAWEDJAWYSJAZZSJAZZYJEANSJEELSJEEPSJEERSJEERYJEFFSJEHUPJEHUSJELABJELLSJELLY
  JEMMYJENNAJENNYJEREZJERIBJERKSJERKYJERLSJERMSJERRYJERTSJESSSJESTSJETESJETTYJEWEL
  JHEELJHOOLJHOWSJIBBYJIBESJIBISJIBOAJIFFSJIFFYJIGGYJIHADJILTSJIMMYJIMPSJINASJINGO
  JINGSJINJAJINKSJINNIJINNSJINNYJINXSJIQUIJIRGAJITISJITROJIVASJIVESJIXIEJOBOSJOCHS
  JOCKOJOCKSJOCUMJOCUSJODELJOEYSJOINSJOINTJOISTJOKERJOKESJOKULJOKYSJOLLSJOLLYJOLTS
  JOLTYJOOLAJOOMSJOREEJORUMJOSHIJOSHSJOSIEJOSSSJOTASJOTTYJOUGHJOUGSJOUKSJOULEJOURS
  JOUSTJOWARJOWELJOWERJOWLSJOWLYJOWPYJUBASJUBBEJUBESJUCKSJUDEXJUDGEJUDOSJUFTIJUGAL
  JUGERJUGUMJUICEJUICYJUJUSJUKESJULEPJULIDJULIOJUMBAJUMBOJUMBYJUMMAJUMPSJUMPYJUNES
  JUNKSJUNTAJUNTOJUNTSJUPESJUPONJURALJURATJURELJURESJURORJURYSJUSTOJUSTSJUTESJUTKA
  JUTTYJUVIAJYNXSKABELKADOSKAFIRKAFIZKAFTAKAGOSKAGUSKAHARKAHASKAHAUKAHUSKAIDSKAIKS
  KAILSKAIWIKAKARKAKASKAKISKAKKEKALASKALESKALISKALONKALOSKAMAOKAMASKAMESKAMIKKANAE
  KANAPKANASKANATKANDEKANEHKANGAKANGSKANSSKAPAIKAPASKAPOKKAPPAKAPPEKAPPSKAPURKAPUT
  KARBIKARCHKARMAKAROSKAROUKARRIKARSTKASASKASHIKASMSKASSUKATARKATHAKATHSKATUNKAURI
  KAVASKAYAKKAYOSKAZISKAZOOKEACHKEAWEKEBABKECKSKECKYKEDGEKEECHKEEKSKEELSKEENAKEENS
  KEEPSKEESTKEETSKEEVEKEFIRKEITAKELDSKELEHKELEKKELEPKELESKELKSKELLAKELLSKELLYKELPS
  KELPYKELTSKELTYKEMBSKEMPSKEMPTKEMPYKENAFKENCHKENDSKENNOKENOSKENTSKEPISKEPTSKERAT
  KERELKERFSKERNSKERRYKETALKETASKETCHKETENKETOLKETOSKETTEKETTYKETYLKEUPSKEVELKEXYS
  KEYEDKHADIKHAIRKHAJAKHAKIKHANSKHARSKHASSKHATSKHETSKHIRSKHOJAKHOKAKHOTSKHULAKHVAT
  KIACKKIAKIKIANGKIBEIKIBESKIBYSKICKSKIDDYKIELSKIERSKIEYEKIKARKIKESKIKISKIKUSKILAH
  KILANKILEHKILEYKILIMKILLSKILLYKILNSKILOSKILPSKILTSKINAHKINASKINCHKINDSKINGSKINKS
  KINKYKINOSKIOEAKIOSKKIPESKIPPYKIRISKIRKSKIRNSKIRVEKISHSKISHYKISRAKISSSKISSYKISTS
  KISWAKITABKITARKITESKITHEKITHSKITTYKIVASKIVERKIVUSKIWISKIYASKIYISKLAMSKLIPSKLOMS
  KLOPSKLOSHKMETSKNABSKNACKKNAGSKNAPEKNAPSKNARKKNARSKNAVEKNEADKNEEDKNEELKNEESKNELL
  KNELTKNETSKNEWSKNEZIKNEZSKNIAZKNICKKNIFEKNITSKNOBSKNOCKKNOLLKNOPSKNOSPKNOTSKNOUT
  KNOWEKNOWNKNOWSKNUBSKNURLKNURSKNUTSKNYAZKOAESKOALAKOALIKOBANKOBISKOBUSKODAKKODAS
  KODROKOELSKOFFSKOFTSKOHLSKOHUAKOILAKOILSKOINEKOKAMKOKANKOKILKOKIOKOKOSKOKRAKOKUM
  KOKUSKOLASKOLEAKOLOSKOMBUKONAKKONASKONGUKOOKAKOPHSKOPISKOPPAKORASKORECKORESKORIN
  KORISKOSINKOTALKOTOSKOUZAKOVILKOYANKOZOSKRAALKRAFTKRAITKRALSKRAMAKRANSKRASSKRAUT
  KREISKREMSKRENGKRINAKROMEKRONAKRONEKROONKROSAKUANSKUBASKUBBAKUDOSKUDUSKUDZUKUEIS
  KUGELKUGESKUKRIKUKUIKUKUSKULAHKULAKKULASKULMSKUMBIKUNAIKUNGSKUNKSKURUSKUSAMKUSAS
  KUSHAKUSTIKUSUMKVASSKVINTKWANSKYACKKYAHSKYARSKYATSKYLESKYLIXKYTESLAANGLABBALABEL
  LABIALABISLABORLABRALACCALACEDLACERLACESLACETLACHELACISLACKSLACTOLACYSLADENLADER
  LADESLADLELADYSLAETILAETSLAGANLAGENLAGERLAGNALAICHLAICSLAIDSLAIGHLAINELAINSLAIRD
  LAIRSLAIRYLAITYLAKERLAKESLAKIELAKYSLALLSLALOSLAMASLAMBALAMBSLAMBYLAMELLAMESLAMIA
  LAMINLAMMYLAMPSLANASLANAZLANCELANDSLANESLANEYLANGILANKSLANKYLANTSLANUMLANXSLAPEL
  LAPONLAPSELAPSILARCHLARDSLARDYLARGELARGOLARIDLARINLARISLARKSLARKYLARRYLARVALARVE
  LASASLASERLASHSLASKSLASSOLASSSLASTSLASTYLATAHLATASLATCHLATEDLATENLATERLATESLATEX
  LATHELATHSLATHYLATROLATUSLAUANLAUDSLAUGHLAUIALAUNDLAUNSLAURALAURSLAVASLAVERLAVES
  LAVICLAWKSLAWNSLAWNYLAWZYLAXLYLAYERLAYNELAZARLAZESLAZYSLEACHLEADSLEADYLEAFSLEAFY
  LEAKSLEAKYLEALSLEAMSLEANSLEANTLEAPSLEAPTLEARNLEARSLEASELEASHLEASTLEATHLEATSLEAVE
  LEAVYLEBANLECHSLECKSLEDENLEDESLEDGELEDGYLEDOLLEECHLEEDSLEEKSLEEKYLEEPSLEERSLEERY
  LEESSLEETSLEFTSLEGALLEGERLEGESLEGGYLEGITLEGOALEGUALEHRSLEHUALEKHALEMANLEMELLEMMA
  LEMONLEMURLENADLENCHLENDSLENESLENISLENOSLENSSLENTHLENTOLENTSLEPASLEPERLEPRALEROT
  LERPSLESIYLESSNLESSSLESTSLETCHLETESLETUPLEUCHLEUCOLEUDSLEUKSLEUMALEVEELEVELLEVER
  LEVINLEVIRLEVOSLEVYSLEWDSLEWISLEWTHLEXIALIANALIANGLIARDLIARSLIBELLIBERLIBRALICCA
  LICESLICHILICHSLICITLICKSLIDOSLIEDSLIEFSLIEGELIENSLIERSLIESHLIEUELIEUSLIEVELIFER
  LIFESLIFEYLIFOSLIFTSLIGASLIGHTLIGNELIINSLIJASLIKENLIKERLIKESLIKINLILACLILESLILLS
  LILTSLILYSLIMANLIMBOLIMBSLIMBYLIMENLIMERLIMESLIMEYLIMITLIMMALIMMULIMNSLIMOSLIMPS
  LIMPYLIMSYLIMUSLIMYSLINASLINCHLINDOLINEALINEDLINENLINERLINESLINGALINGELINGOLINGS
  LINGYLINHALINIELININLINJALINJELINKSLINKYLINNSLINONLINOSLINTSLINTYLINYSLIONSLIPAS
  LIPINLIPPYLIRASLIRESLISHSLISKSLISLELISPSLISSSLISTSLITASLITCHLITERLITESLITHELITHI
  LITHOLITHSLITHYLITRALITUSLITZSLIVEDLIVENLIVERLIVESLIVIDLIVORLIVRELIWANLLAMALLANO
  LLYNSLOACHLOADSLOAFSLOAMSLOAMYLOANSLOATHLOAVELOBALLOBARLOBBYLOBEDLOBESLOBOSLOCAL
  LOCASLOCHSLOCHYLOCISLOCKSLOCKYLOCOSLOCUMLOCUSLODESLODGELOESSLOFTSLOFTYLOGESLOGIA
  LOGICLOGIELOGINLOGOILOGOSLOGYSLOHANLOINSLOIRSLOKAOLOKASLOKESLOKETLOLLSLOLLYLOMAS
  LONESLONGALONGELONGSLOOBYLOODSLOOFSLOOKSLOOMSLOONSLOONYLOOPSLOOPYLOOSELOOTSLOPER
  LOPESLOPPYLORALLORANLORASLORDSLORDYLOREDLORESLORICLORISLORNSLOROSLORRYLORSSLORUM
  LORYSLOSELLOSERLOSESLOSHSLOSSSLOSTSLOTASLOTESLOTICLOTSSLOTTOLOTUSLOUCHLOUDSLOUEY
  LOUGHLOUKSLOULULOUPELOUPSLOURSLOUSELOUSYLOUTSLOUTYLOVERLOVESLOWANLOWASLOWERLOWLY
  LOWNSLOWTHLOWYSLOXIALOXICLOYALLUBESLUBRALUCESLUCETLUCIDLUCKSLUCKYLUCRELUCYSLUDOS
  LUESSLUFFSLUGERLUGESLUKESLULABLULLSLULUSLUMENLUMMYLUMPSLUMPYLUNARLUNASLUNCHLUNES
  LUNGELUNGILUNGSLUNGYLUNNSLUNTSLUPESLUPISLUPUSLURALLURASLURCHLURERLURESLURGSLURID
  LURKSLURKYLURRYLUSHSLUSHYLUSKSLUSKYLUSTSLUSTYLUTEOLUTERLUTESLUXESLUXUSLYAMSLYARD
  LYCIDLYERYLYINGLYMPHLYNCHLYNXSLYRASLYRESLYRICLYSESLYSINLYSISLYSSALYTICLYTTAMAAMS
  MABISMACANMACAOMACAWMACCOMACERMACESMACHIMACKSMACLEMACOSMACROMADAMMADESMADIDMADLY
  MADOSMAFICMAFOOMAGASMAGESMAGICMAGISMAGMAMAGOTMAHARMAHASMAHOEMAHUAMAIDSMAIDYMAIID
  MAILSMAIMSMAINSMAINTMAIREMAIZEMAJORMAJOSMAKERMAKESMAKISMAKOSMAKUKMALARMALASMALAX
  MALEOMALESMALICMALIKMALISMALLSMALMSMALMYMALOSMALTSMALTYMAMBAMAMBOMAMMAMAMMYMAMOS
  MANALMANASMANDSMANEDMANEIMANESMANEYMANGAMANGEMANGIMANGOMANGSMANGYMANIAMANICMANID
  MANISMANIUMANKSMANLYMANNAMANNYMANOCMANORMANOSMANSEMANSOMANTAMANTOMANTSMANULMANUS
  MANYSMAPAUMAPLEMAPOSMAPPYMAQUIMARAEMARALMARCHMARCOMARCSMARDYMARESMARGEMARIAMARID
  MARISMARKAMARKSMARLIMARLSMARLYMARMSMAROKMAROSMARRYMARSHMARTSMARUSMARYSMASASMASHA
  MASHSMASHYMASKSMASONMASSAMASSEMASSSMASSYMASTSMASTYMASUSMATAIMATAXMATCHMATERMATES
  MATEYMATHSMATINMATKAMATRAMATSUMATTAMATTEMATTIMATYSMATZOMAUDSMAUGHMAULSMAUNDMAUNS
  MAUVEMAUXSMAVISMAWKSMAWKYMAWPSMAXIMMAYASMAYBEMAYNTMAYORMAZASMAZEDMAZERMAZESMAZIC
  MAZUTMAZYSMBORIMEADSMEAKSMEALSMEALYMEANSMEANTMEASEMEATSMEATYMECONMEDALMEDIAMEDIC
  MEDIOMEECEMEEDSMEEKSMEESEMEETSMEILEMEINSMEIOSMEITHMELAMMELASMELCHMELDSMELEEMELES
  MELICMELLSMELOEMELONMELOSMELTSMEMOSMENDSMENGSMENSAMENSEMENSKMENUSMENYSMERCHMERCY
  MERELMERESMERGEMERGHMERILMERITMERKSMERLEMERLSMEROPMEROSMERRYMERSEMESADMESALMESAS
  MESEMMESESMESHSMESHYMESICMESNEMESONMESOSMESSEMESSSMESSYMETADMETALMETASMETELMETER
  METESMETICMETISMETRAMETZEMEUSEMEUTEMEWERMEWLSMEZZOMIANSMIAOWMIASMMIASSMIAULMICAS
  MICESMICHEMICHTMICKSMICOSMICROMIDDYMIDESMIDGEMIDGYMIDSSMIDSTMIENSMIFFSMIFFYMIGHT
  MIJLSMIKESMIKIEMILASMILCHMILDSMILERMILESMILHAMILKSMILKYMILLAMILLEMILLSMILOSMILPA
  MILTSMILTYMIMASMIMEOMIMERMIMESMIMICMIMLYMIMPSMINARMINASMINCEMINDSMINERMINESMINGE
  MINGSMINGYMINIMMINKSMINNYMINORMINOSMINOTMINTSMINTYMINUSMINXSMINYSMIQRAMIRDSMIRES
  MIRIDMIRKSMIROSMIRTHMIRYSMIRZAMISDOMISERMISESMISGOMISKYMISSSMISSYMISTSMISTYMITER
  MITESMITISMITRAMITREMITTSMITTYMITYSMIXEDMIXENMIXERMIXYSMIZZYMNEMEMOANSMOATSMOBBY
  MOBEDMOBLEMOCHAMOCKSMODALMODELMODESMOFFSMOGGYMOGOSMOHARMOHASMOHELMOHOSMOHRSMOHUR
  MOILSMOIOSMOIREMOISEMOISTMOITSMOITYMOJOSMOKESMOKISMOKOSMOKUMMOKYSMOLALMOLARMOLAS
  MOLDSMOLDYMOLERMOLESMOLKAMOLLEMOLLSMOLLYMOLPEMOLTSMOLYSMOMESMOMMEMOMMYMOMOSMONAD
  MONALMONASMONELMONERMONESMONEYMONGSMONKSMONNYMONOSMONTEMONTHMOOCHMOODSMOODYMOOLS
  MOONSMOONYMOOPSMOORNMOORSMOORYMOOSAMOOSEMOOSTMOOTHMOOTSMOPERMOPESMOPHSMOPLAMOPPY
  MOPSYMOPUSMORALMORASMORATMORAYMORELMORESMORGAMORGSMORICMORINMORMOMORNEMORNSMOROC
  MORONMOROSMORPHMORSEMORTHMORTSMOSEYMOSSSMOSSYMOSTEMOSTSMOTEDMOTELMOTERMOTESMOTET
  MOTEYMOTHSMOTHYMOTIFMOTORMOTTEMOTTOMOTTSMOUDSMOUDYMOULDMOULEMOULSMOULYMOUNDMOUNT
  MOUPSMOURNMOUSEMOUSYMOUTHMOUTSMOVERMOVESMOVIEMOWCHMOWERMOWHAMOWIEMOWNSMOWRAMOWSE
  MOWTHMOWTSMOXASMOYENMOYLEMOYOSMPRETMUANGMUCHSMUCICMUCIDMUCINMUCKSMUCKYMUCORMUCRO
  MUCUSMUDARMUDDEMUDDSMUDDYMUDEEMUDIRMUDRAMUFFSMUFFYMUFTIMUFTYMUGASMUGGSMUGGYMUIDS
  MUIRSMUISTMUKTIMULCHMULCTMULESMULEYMULGAMULKSMULLAMULLSMULSEMULTSMUMMYMUMPSMUNCH
  MUNDSMUNGAMUNGEMUNGOMUNGSMUNGYMUNJSMUNTSMURALMURASMURESMUREXMURGAMURIDMURKSMURKY
  MURLYMURRAMURREMURVAMURZAMUSALMUSARMUSEDMUSERMUSESMUSHAMUSHSMUSHYMUSICMUSIEMUSKS
  MUSKYMUSSSMUSSYMUSTSMUSTYMUTASMUTCHMUTESMUTHSMUTICMUTTSMUZZSMUZZYMYALLMYALSMYNAS
  MYOIDMYOMAMYOPEMYOPSMYOPYMYRONMYRRHMYSELMYSIDMYSTSMYTHSMYXASMYXOSNAAMSNABAKNABKS
  NABLANABLENABOBNABSSNACESNACHSNACRENACRYNADIRNAELSNAGASNAGGYNAGHTNAGORNAIADNAIDS
  NAIFSNAIGSNAIKSNAILSNAILYNAINSNAIOSNAIRYNAISHNAISSNAIVENAKEDNAKERNAKESNAKOONAKOS
  NAMAZNAMDANAMERNAMESNANASNANCYNANDINANDUNANESNANGANANNYNANTSNAOSSNAPALNAPASNAPES
  NAPOONAPPENAPPYNAPUSNARDSNARESNARICNARKSNARKYNARRANARRSNARYSNASABNASALNASCHNASHS
  NASISNASTSNASTYNASUSNATALNATCHNATESNATHENATRSNATTYNAUMKNAUNTNAUTSNAVALNAVARNAVEL
  NAVESNAVETNAVEWNAVVYNAVYSNAWABNAWTSNAZESNAZIMNAZIRNEALSNEAPSNEARSNEATHNEATSNEBBY
  NEBELNECKSNEDDYNEEDSNEEDYNEELDNEELENEEMSNEEPSNEERSNEESENEETSNEEZENEFFYNEGERNEGRO
  NEGUSNEIFSNEIGHNEISTNEMASNENTANEONSNEOZANEPERNERVENERVYNESESNESHSNESSSNESTSNESTY
  NETERNETESNETHSNETISNETOPNETTYNEUMANEUMENEVELNEVERNEVESNEVOSNEVOYNEVUSNEWELNEWLY
  NEWSSNEWSYNEWTSNEXALNEXTSNEXUMNEXUSNGAIONGAISNGAPINIATANIBBYNIBSSNICESNICHENICKS
  NICKYNIDALNIDESNIDGENIDISNIDORNIDUSNIECENIEPANIEVENIFESNIFICNIFLENIFTYNIGHSNIGHT
  NIGRENIGUANIKAUNIMBINIMBSNINESNINNYNINONNINTHNINTUNINUTNIOGSNIOTANIPASNIPPYNISEI
  NISSENISUSNITCHNITERNITIDNITONNITOSNITRONITTYNIVALNIXIENIZAMNIZYSNJAVENOBBYNOBLE
  NOBLYNOBSSNOCKSNODALNODDYNODEDNODESNODISNODUSNOELSNOGALNOHOWNOILSNOILYNOINTNOIRS
  NOISENOISYNOKTANOLLENOLLSNOLOSNOMADNOMASNOMESNOMICNOMOSNONCENONDANONDONONESNONET
  NONICNONLYNONYANONYLNOOKSNOOKYNOONSNOOPSNOOSENOPALNOPESNORIANORIENORISNORMANORMS
  NORTHNOSEDNOSERNOSESNOSEYNOSHSNOSYSNOTALNOTANNOTCHNOTEDNOTERNOTESNOTUMNOUNSNOUPS
  NOUSSNOVASNOVELNOVEMNOWAYNOWEDNOWELNOWTSNOWYSNOXALNOXASNOYAUNUBBYNUBIANUCALNUCHA
  NUCINNUDESNUDGENUKESNULLONULLSNUMBSNUMDANUMENNUMMINUMUDNUNCHNUNKYNUNNINUQUENURLY
  NURSENURSYNUTTYNYLONNYMILNYMPHNYXISOADALOAKENOAKUMOAKYSOAREDOARICOARYSOASALOASES
  OASISOASTSOATENOATHSOATYSOBANSOBEAHOBESEOBEXSOBEYSOBITSOBLEYOBOESOBOLEOBOLSOCCUR
  OCEANOCHEROCHROOCHTSOCOTEOCQUEOCREAOCTADOCTANOCTETOCTICOCTYLOCUBYODALSODDLYODDSS
  ODELSODEONODEUMODICSODISTODIUMODOOMODORSODSOSODUMSODYLSOECUSOENINOFFALOFFEROFTEN
  OFTEROFTLYOGAMSOGEEDOGEESOGHAMOGIVEOGLEROGLESOGMICOGRESOGUMSOHELOOHIASOHMICOHOYS
  OILEDOILEROILYSOIMESOINTSOISINOKAPIOKEESOKETSOKIASOKRASOKRUGOLAMSOLDENOLDEROLDIE
  OLEICOLEINOLENAOLENTOLEOSOLIDSOLIOSOLIVAOLIVEOLLASOLOGYOLONAOLPESOMAOSOMBEROMEGA
  OMENSOMERSOMINAOMITSOMLAHONCASONCESONCIAONCINONDYSONERSONERYONIONONIUMONKOSONLAY
  ONLYSONSETONTALONTOSONUSSONYMSONYMYONYXSONZASOOFYSOOIDSOOLAKOOLLYOONSSOONTSOOPAK
  OOPODOORDSOOTIDOOZESOOZYSOPAHSOPALSOPENSOPERAOPHICOPINEOPIUMOPSYSOPTICOPUSSORACH
  ORADSORAGEORALSORANGORANTORARYORATEORBEDORBICORBITORBYSORCINORDERORDUSOREADORGAN
  ORGIAORGICORGUEORGYSORIBIORIELORLESORLETORLOPORLOSORMERORNASORNISORRISORSELORTET
  ORTHOOSCINOSELAOSHACOSIDEOSIEROSMICOSMINOSONEOSSALOSSESOTARYOTATEOTHEROTICSOTKON
  OTTAROTTEROTTOSOUABEOUCHSOUGHSOUGHTOUKIAOULAPOUNCEOUNDSOUPHEOURIEOURSSOUSTSOUTBY
  OUTDOOUTEDOUTENOUTEROUTGOOUTLYOUTREOUZELOVALSOVANTOVARYOVATEOVENSOVERSOVERTOVEST
  OVEYSOVILEOVINEOVISMOVISTOVOIDOVOLOOVULEOVUMSOWERSOWGHTOWINGOWLEROWLETOWLYSOWNER
  OWSENOWSEROWSESOXANEOXANSOXBOWOXBOYOXEASOXENSOXERSOXEYEOXFLYOXIDEOXIMEOXLIPOXMAN
  OXTEROXYLSOYERSOZENAOZONEPAALSPAARSPAAUWPABLOPACASPACAYPACEDPACERPACESPACKSPACOS
  PACTSPADDYPADGEPADLEPADREPAEANPAEONPAGANPAGASPAGERPAGESPAGUSPAHASPAHISPAHMIPAHOS
  PAIKSPAILSPAINSPAINTPAIPSPAIRSPAISAPAISSPALARPALASPALAYPALCHPALEAPALEDPALERPALES
  PALETPALISPALLAPALLIPALLSPALLYPALMAPALMOPALMSPALMYPALPIPALPSPALSYPALTSPALUSPALYS
  PANAXPANDAPANDSPANDYPANEDPANELPANESPANGIPANGSPANICPANKSPANNEPANSEPANSYPANTOPANTS
  PANTYPAOLOPAONSPAPALPAPASPAPAWPAPERPAPESPAPEYPAPPIPAPPYPAPYRPARAHPARAMPARAOPARAS
  PARCHPARDOPARDSPARELPARENPARERPARESPARGEPARGOPARISPARKAPARKSPARKYPARLEPARLYPARMA
  PAROLPARRSPARRYPARSEPARTOPARTSPARTYPASANPASHAPASHMPASHSPASISPASMOPASSEPASSOPASSS
  PASTEPASTSPASTYPASULPATAOPATASPATCHPATELPATENPATERPATESPATHSPATHYPATIOPATLYPATOS
  PATTAPATTEPATTUPATTYPATUSPATYSPAUPSPAUSEPAUTSPAUXIPAVANPAVERPAVESPAVIDPAVISPAVYS
  PAWERPAWKSPAWKYPAWLSPAWNSPAYEDPAYEEPAYERPAYORPEACEPEACHPEAGEPEAGSPEAISPEAKSPEAKY
  PEALSPEANSPEARLPEARSPEARTPEASYPEATSPEATYPEAVYPEBASPECANPECHSPECHTPECKSPECKYPEDAL
  PEDASPEDEEPEDESPEDROPEDUMPEEDSPEEKSPEELEPEELSPEENSPEEOYPEEPSPEEPYPEERSPEERYPEEVE
  PEGASPEGGYPEHOSPEINEPEISEPEKANPEKINPEKOEPELFSPELLSPELONPELTAPELTSPELUSPENALPENCE
  PENDAPENDSPENGOPENISPENKSPENNAPENNIPENNYPENSYPENTAPENTSPEONSPEONYPEPOSPEPPYPERCH
  PERDUPERESPERILPERISPERITPERKSPERKYPERLEPERMSPERNSPERRYPERSEPERTSPERTYPESASPESKY
  PESOSPESSSPESTEPESTSPETALPETERPETESPETITPETOSPETREPETTYPEUHLPEWEEPEWITPEWYSPFUIS
  PFUNDPHAGEPHANOPHAREPHASEPHASMPHEALPHENEPHEONPHEWSPHIALPHITSPHIZSPHOBYPHOCAPHOHS
  PHONEPHONOPHONSPHONYPHOOSPHOSEPHOSSPHOTOPHOTSPHUTSPHYLAPHYLEPHYMAPIABAPIALSPIANO
  PIANSPICALPICASPICESPICHIPICKSPICKYPICOSPICOTPICRAPICTSPICULPIDANPIECEPIEDSPIEND
  PIENSPIERSPIETSPIETYPIEZOPIFFSPIGGYPIGLYPIKASPIKEDPIKELPIKERPIKESPIKEYPIKISPIKLE
  PIKYSPILARPILAUPILCHPILEDPILERPILESPILINPILISPILLSPILMSPILMYPILONPILOTPILUMPILUS
  PILYSPIMPSPINASPINAXPINCHPINDAPINDSPINDYPINEDPINERPINESPINEYPINGSPINICPINKSPINKY
  PINNAPINNYPINONPINOSPINTAPINTEPINTOPINTSPINYLPINYSPIOUSPIPALPIPASPIPEDPIPERPIPES
  PIPETPIPISPIPITPIPPYPIPYSPIQUEPIRLSPIRNSPIRNYPIROLPIRRSPISAYPISCOPISESPISHSPISHU
  PISKSPISKYPISOSPISSSPISTSPITASPITAUPITCHPITHSPITHYPITYSPIURIPIVOTPIXIEPIXYSPIZES
  PIZZAPLACEPLACKPLAGAPLAGEPLAIDPLAINPLAITPLAKSPLANEPLANGPLANKPLANSPLANTPLAPSPLASH
  PLASMPLASSPLATEPLATSPLATYPLAUDPLAYAPLAYSPLAZAPLEADPLEASPLEATPLEBEPLEBSPLECKPLEDS
  PLENYPLEONPLEWSPLEXSPLICAPLIEDPLIERPLIESPLIMSPLOATPLOCEPLOCKPLODSPLOMBPLOOKPLOPS
  PLOTEPLOTSPLOUKPLOUTPLOWSPLOYSPLUCKPLUDSPLUFFPLUGSPLUMAPLUMBPLUMEPLUMPPLUMSPLUMY
  PLUNKPLUPSPLUSHPLUSSPLYERPOACHPOBBYPOBSSPOCHEPOCKSPOCKYPOCOSPODALPODDYPODEXPODGE
  PODGYPOEMSPOESYPOETSPOGGEPOGGYPOGYSPOHASPOHNAPOILSPOILUPOINDPOINTPOISEPOKEDPOKER
  POKESPOKEYPOKYSPOLARPOLERPOLESPOLEYPOLIOPOLISPOLKAPOLKSPOLLSPOLOSPOLTSPOLYPPOLYS
  POMBEPOMBOPOMESPOMEYPOMMEPOMMYPOMPAPOMPSPONCEPONDSPONDYPONESPONEYPONGAPONGSPONJA
  PONTOPONTSPONYSPOOASPOOCHPOOFSPOOHSPOOKAPOOKSPOOLIPOOLSPOOLYPOONSPOOPSPOORSPOOTS
  POPALPOPESPOPPAPOPPYPORALPORCHPOREDPORERPORESPORGEPORGYPORKSPORKYPOROSPORRSPORRY
  PORTAPORTOPORTSPORTYPORUSPORYSPOSCAPOSERPOSESPOSEYPOSHSPOSITPOSSEPOSSSPOSTSPOSYS
  POTCHPOTERPOTESPOTOOPOTTOPOTTSPOTTYPOUCEPOUCHPOUFSPOULPPOULTPOUNDPOURSPOUTSPOUTY
  POWERPOXYSPOYOUPRAAMPRADSPRAMSPRANAPRANKPRASEPRATEPRATSPRAUSPRAWNPRAYAPRAYSPREEN
  PREPSPRESSPRESTPREXYPREYSPRICEPRICHPRICKPRIDEPRIDYPRIEDPRIERPRIGSPRILLPRIMAPRIME
  PRIMPPRIMSPRIMYPRINEPRINKPRINTPRIONPRIORPRISMPRISSPRIUSPRIVYPRIZEPROALPROASPROBE
  PROBSPRODSPROEMPROFSPROGSPROKEPRONEPRONGPROOFPROOSPROPSPROREPROSEPROSOPROSSPROSY
  PROTEPROTOPROUDPROVEPROWLPROWSPROXYPRUDEPRUHSPRUNEPRUNTPRUTSPRYERPRYSEPSALMPSHAS
  PSHAWPSOASPSORAPSYCHPUANSPUBALPUBESPUBICPUBISPUCESPUCKAPUCKSPUDDYPUDGEPUDGYPUDIC
  PUDSYPUDUSPUFFSPUFFYPUGGIPUGGYPUGHSPUGILPUISTPUJASPUKASPUKERPUKESPUKKAPUKUSPUKYS
  PULERPULESPULISPULKAPULKSPULLIPULLSPULPSPULPYPULSEPULUSPULYSPUMASPUMPSPUNASPUNCH
  PUNCTPUNGAPUNGIPUNGSPUNKSPUNKYPUNTAPUNTIPUNTOPUNTSPUNTYPUNYSPUPALPUPASPUPILPUPPY
  PURDYPUREDPUREEPURERPURESPURGAPURGEPURLSPURREPURRSPURRYPURSEPURSYPUSHSPUSSSPUSSY
  PUTIDPUTTSPUTTYPUXYSPYALSPYCHEPYGALPYGMYPYICSPYINSPYKESPYLARPYLASPYLICPYLONPYOID
  PYRALPYRANPYRESPYREXPYROSPYXIEPYXISQERESQERISQOPHSQUABSQUACKQUADSQUAFFQUAGSQUAIL
  QUAKEQUAKYQUALEQUALMQUANSQUANTQUAREQUARKQUARLQUARSQUARTQUASHQUASIQUATAQUATSQUAUK
  QUAVEQUAWKQUAWSQUAYSQUBBAQUEAKQUEALQUEANQUEENQUEERQUEETQUEGHQUEISQUELLQUEMEQUERL
  QUERNQUERYQUESTQUETSQUEUEQUEYSQUIBSQUICAQUICKQUIDSQUIETQUIFFQUILAQUILLQUILTQUINA
  QUINKQUINSQUINTQUIPOQUIPSQUIPUQUIRAQUIREQUIRKQUIRLQUIRTQUISSQUITEQUITSQUIZSQUODS
  QUOINQUOITQUOPSQUOTAQUOTEQUOTHQUOTSRAADSRAASHRABATRABBIRABICRABIDRACERRACESRACHE
  RACHSRACKSRACONRACYSRADARRADASRADIIRADIORADIXRADONRAFFERAFFSRAFTSRAFTYRAGASRAGER
  RAGESRAGGYRAIASRAIDSRAILSRAINSRAINYRAISERAISSRAJAHRAJASRAKANRAKERRAKESRAKHSRAKIS
  RAKITRAKUSRALESRALLYRALPHRAMALRAMEDRAMESRAMETRAMEXRAMIERAMISRAMMYRAMPSRAMUSRANAL
  RANASRANCERANCHRANDSRANDYRANESRANGERANGSRANGYRANIDRANISRANKSRANNSRANNYRANTSRANTY
  RAPERRAPESRAPHERAPICRAPIDRAPPERAPTSRARESRASASRASENRASERRASESRASHSRASPSRASPYRASSE
  RATALRATASRATCHRATEDRATELRATERRATESRATHERATHSRATIORATTIRATTYRATWARAUKSRAULIRAUNS
  RAUPORAVELRAVENRAVERRAVESRAVINRAYASRAYEDRAYONRAZEERAZERRAZESRAZOORAZORRAZZSREAAL
  REACHREACTREADDREADSREADYREAKSREALMREALSREAMSREAMYREAPSREARMREARSREASKREASYREAVE
  REBABREBAGREBANREBARREBECREBEDREBEGREBELREBIAREBIDREBOBREBOPREBOXREBUDREBUSREBUT
  REBUYRECAPRECCERECCORECCYRECKSRECONRECTARECTIRECTORECTSRECURRECUTREDANREDDSREDDY
  REDESREDIAREDIDREDIGREDIPREDLYREDOSREDOXREDRYREDUBREDUEREDUXREDYEREEDSREEDYREEFS
  REEFYREEKSREEKYREELSREEMSREENSREESEREESKREESTREETSREEVEREFANREFELREFERREFITREFIX
  REFLYREFTSREGALREGESREGETREGIAREGINREGLEREGMAREGURREHOEREIFSREIFYREIGNREIMSREINA
  REINSREISSREITSRELAPRELAXRELAYRELETRELICRELOTRELYSREMANREMAPREMEXREMITREMIXREMOP
  RENALRENDSRENEGRENESRENETRENEWRENINRENKSRENKYRENNERENTSREOILREOWNREPAYREPEGREPEL
  REPENREPEWREPICREPINREPLYREPOTREPPSREPSSREREERERIGREROBREROWRERUBRERUNRESAWRESAY
  RESEERESETRESEWRESEXRESHSRESINRESOWRESPSRESTSRESTYRESUERESUNRESUPRETAGRETANRETAX
  RETCHRETEMRETHERETIARETIERETINRETIPRETRYREUNEREUSEREVELREVERREVESREVETREVIEREVUE
  REWAXREWEDREWETREWINREXENRHAMNRHEASRHEENRHEICRHEINRHEMARHEMERHEUMRHINERHINORHOMB
  RHUMBRHYMERHYMYRIALSRIANTRIATARIBATRIBBYRIBESRICERRICESRICEYRICHSRICHTRICINRICKS
  RIDENRIDERRIDESRIDGERIDGYRIEMSRIERSRIFESRIFFSRIFLERIFTSRIFTYRIGHTRIGIDRIGOLRIGOR
  RIKKSRILESRILEYRILLSRILLYRIMALRIMASRIMERRIMESRIMPIRIMUSRIMYSRINCHRINDSRINDYRINES
  RINGERINGSRINGYRINKARINKSRINSERIOTSRIPALRIPASRIPENRIPERRIPESRIPUPRISENRISERRISES
  RISHIRISKSRISKYRISPSRISTSRITASRITESRITZYRIVALRIVASRIVELRIVENRIVERRIVESRIVETRIXYS
  RIYALROACHROADSROAMSROANSROARSROASTROBERROBESROBINROBLEROBOTROBURROCKSROCKYROCTA
  RODDSRODEORODESRODGEROEDSROERSROEYSROGANROGERROGUEROHANROHOBROHUNROIDSROILSROILY
  ROITSROKASROKEEROKERROKESROKEYROKYSROLEOROLESROLLSROMALROMANROMPSROMPUROMPYRONCO
  RONDERONDORONDSRONESROODSROOFSROOFYROOKSROOKYROOLSROOMSROOMYROONSROOSAROOSTROOTS
  ROOTYROOVEROPERROPESROPPSROPYSROQUERORALRORICRORTYRORYSROSALROSEDROSELROSESROSET
  ROSINROSSSROSYSROTALROTANROTASROTCHROTERROTESROTGEROTORROTOSROUBSROUDSROUESROUGE
  ROUGHROUGYROUKYROUNDROUNSROUPSROUPYROUSEROUSTROUTEROUTHROUTSROVERROVESROVETROWAN
  ROWDYROWEDROWELROWENROWERROWETROWTYROWYSROXYSROYALROYETROYTSROZUMRUACHRUANARUBLE
  RUBORRUBYSRUCHERUCKSRUCKYRUDASRUDDSRUDDYRUDESRUDGERUENSRUERSRUFFSRUFUSRUGASRUGGY
  RUINGRUINSRUKHSRULERRULESRULLSRUMALRUMBORUMENRUMLYRUMMYRUMORRUMPSRUNBYRUNCHRUNED
  RUNERRUNESRUNGSRUNICRUNNYRUNTSRUNTYRUPASRUPEERUPIARUPIERURALRURUSRUSESRUSHSRUSHY
  RUSKSRUSKYRUSMARUSOTRUSTSRUSTYRUTCHRUTHSRUTICRUTINRUTTYRUTYLRUVIDRYALSRYBATRYDER
  RYENSRYMESRYNDSRYNTSRYOTSRYPESSABERSABESSABLESABLYSABOTSABRASABZISACKSSACOSSACRA
  SACROSADESSADHESADHSSADHUSADICSADLYSADOSSADRSSAFENSAFESSAFTSSAGASSAGESSAGGYSAGOS
  SAGUMSAGYSSAHHSSAHIBSAHMESAICSSAIDSSAIGASAILSSAILYSAIMSSAIMYSAINSSAINTSAIPSSAIRS
  SAIRYSAJOUSAKERSAKESSAKISSALADSALALSALARSALATSALAYSALEPSALESSALICSALIXSALLESALLY
  SALMASALOLSALONSALPASALPSSALSESALTASALTSSALTYSALVESALVOSALVYSAMAJSAMANSAMBASAMBO
  SAMELSAMENSAMESSAMHSSAMMYSAMPISAMPSSANAISANCTSANDSSANDYSANESSANGASANGSSANKSSANSI
  SANSSSANTSSAPANSAPASSAPEKSAPIDSAPINSAPLESAPORSAPOSSAPPYSARAFSARDSSARESSARGOSARIF
  SARIPSARISSARKSSARNASARODSARONSAROSSARPOSARRASARSASARTSSARUSSASANSASASSASHSSASIN
  SASSSSASSYSATANSATESSATINSATYRSAUCESAUCYSAUFSSAUGHSAULDSAULTSAUMSSAUNASAURSSAURY
  SAUTESAUTSSAUTYSAUVESAVEDSAVERSAVESSAVINSAVORSAVOYSAVVYSAWAHSAWEDSAWERSAWNSSAWTS
  SAYASSAYERSAYIDSAZENSCABSSCADSSCAFFSCALASCALDSCALESCALLSCALPSCALTSCALYSCAMPSCAMS
  SCANSSCANTSCAPESCAPSSCARESCARFSCARNSCARPSCARSSCARTSCARYSCASESCATSSCAULSCAUMSCAUP
  SCAURSCAUTSCAWDSCAWLSCAWSSCEATSCENASCENDSCENESCENTSCHOSSCHUHSCHWASCINDSCIONSCLAW
  SCLERSCLIMSCOADSCOBSSCOFFSCOGSSCOKESCOLBSCOLDSCONESCOONSCOOPSCOOTSCOPASCOPESCOPS
  SCORESCORNSCOTESCOTSSCOUKSCOUPSCOURSCOUTSCOVESCOVYSCOWLSCOWSSCRABSCRAESCRAGSCRAM
  SCRANSCRAPSCRATSCRAWSCRAYSCREESCREWSCRIMSCRINSCRIPSCROBSCRODSCROGSCROOSCROWSCRUB
  SCRUFSCRUMSCRYSSCUDISCUDOSCUDSSCUFFSCUFTSCUGSSCULLSCULPSCUMSSCUNSSCUPSSCURFSCURS
  SCUSESCUTASCUTESCUTSSCYESSCYTSSEAHSSEAKSSEALSSEAMSSEAMYSEARSSEARYSEATSSEAVESEAVY
  SEAXSSEBUMSECHSSECKSSECOSSECRESECTSSEDANSEDGESEDGYSEDUMSEECHSEEDSSEEDYSEEGESEEKS
  SEELSSEELYSEEMSSEENSSEEPSSEEPYSEERSSEGOLSEGOSSEGUESEINESEISESEISMSEITSSEITYSEIZE
  SEKOSSELAHSELESSELFSSELLASELLSSELLYSELTSSELVASEMENSEMESSEMICSEMISSENAMSENCESENDS
  SENNASENSASENSESENSOSENTSSEPADSEPALSEPIASEPICSEPOYSEPSSSEPTASEPTSSEQUASERABSERAI
  SERALSERASSERAUSERAWSEREHSERESSERFSSERGESERIFSERINSERIOSERMOSERONSEROSSEROWSERRA
  SERRYSERTASERTSSERUMSERUTSERVESERVOSESMASESSSSESTISETAESETALSETASSETHSSETONSETTS
  SETUPSEUGHSEVENSEVERSEWANSEWEDSEWENSEWERSEWNSSEXEDSEXLYSEXTOSEXTSSEXYSSFOOTSHABS
  SHACKSHADESHADSSHADYSHAFTSHAGSSHAHISHAHSSHAKESHAKOSHAKUSHAKYSHALESHALLSHALTSHALY
  SHAMASHAMESHAMSSHANKSHANSSHANTSHAPESHAPSSHAPYSHARDSHARESHARKSHARNSHARPSHATSSHAUL
  SHAUPSHAVESHAWLSHAWMSHAWSSHAWYSHAYSSHEAFSHEALSHEARSHEASSHEATSHEDSSHEENSHEEPSHEER
  SHEESSHEETSHEIKSHELASHELDSHELFSHELLSHENDSHENGSHERSSHETHSHEVASHEWASHICESHIDESHIED
  SHIELSHIERSHIESSHIFTSHIHSSHIKOSHILFSHILLSHIMSSHINESHINSSHINYSHIPSSHIRESHIRKSHIRL
  SHIRRSHIRTSHISHSHISNSHITASHIVESHIVSSHIVYSHOADSHOALSHOATSHOCKSHODESHODSSHOERSHOES
  SHOGISHOGSSHOJISHOLASHOLESHONESHOODSHOOISHOOKSHOOLSHOOPSHOORSHOOSSHOOTSHOPSSHOQS
  SHORESHORNSHORSSHORTSHOTESHOTSSHOTTSHOUSSHOUTSHOVESHOWNSHOWSSHOWYSHOYASHRABSHRAF
  SHRAGSHRAMSHRAPSHREDSHREESHREWSHRIPSHROGSHRUBSHRUGSHUBASHUCKSHUFFSHUGSSHULSSHUNE
  SHUNSSHUNTSHURESHURFSHUSHSHUTSSHYERSHYLYSIAKSSIALSSIBBYSIBYLSICCASICESSICKSSIDED
  SIDERSIDESSIDHESIDISSIDLESIDTHSIDYSSIEGESIERSSIEVESIEVYSIFACSIFESSIFTSSIGHSSIGHT
  SIGILSIGLASIGMASIGNSSIKARSIKASSIKESSIKETSILENSILESSILEXSILKSSILKYSILLSSILLYSILOS
  SILTSSILTYSILVASILYLSIMALSIMARSIMASSIMESSIMPSSINALSINASSINCESINDSSINESSINEWSINGE
  SINGHSINGSSINHSSINKSSINKYSINUSSIOLSSIONSSIPERSIPESSIPIDSIRENSIRESSIRIHSIRISSIRKI
  SIRKYSIROCSIRUPSISALSISELSISESSISHSSISISSISSSSISSYSISTSSITAOSITARSITCHSITESSITHE
  SITHSSITIOSITUSSIVASSIVERSIXERSIXTESIXTHSIXTYSIZALSIZARSIZEDSIZERSIZESSIZYSSIZZS
  SKAFFSKAGSSKAIRSKALSSKARTSKATESKATSSKAWSSKEANSKEEDSKEEGSKEELSKEENSKEERSKEESSKEET
  SKEGSSKEIFSKEINSKELFSKELLSKELPSKELSSKEMPSKENESKENSSKEOSSKEPSSKERESKERSSKETESKEWL
  SKEWSSKEWYSKEYSSKICESKIDSSKIEDSKIERSKIESSKIFFSKIFTSKILLSKILSSKIMESKIMPSKIMSSKINK
  SKINSSKIPSSKIRLSKIRPSKIRRSKIRTSKITESKITSSKIVESKIVSSKOALSKOOSSKOUTSKUASSKULKSKULL
  SKULPSKUNKSKUNSSKUSESKYEYSKYRESLABSSLACKSLADESLADSSLAESSLAGSSLAINSLAITSLAKESLAKY
  SLAMPSLAMSSLANESLANGSLANKSLANTSLAPESLAPSSLARESLARTSLASHSLATESLATHSLATSSLATYSLAUM
  SLAVESLAWSSLAYSSLECKSLEDSSLEEKSLEEPSLEERSLEESSLEETSLENTSLEPTSLETESLEWSSLEYSSLICE
  SLICHSLICKSLIDESLIDSSLIMESLIMSSLIMYSLINESLINGSLINKSLIPESLIPSSLIRTSLISHSLITESLITS
  SLIVESLOANSLOBSSLOCKSLODSSLOESSLOGSSLOKASLOKESLONESLONKSLONSSLOOMSLOOPSLOOSSLOPE
  SLOPSSLOPYSLORPSLOSHSLOTESLOTHSLOTSSLOURSLOWSSLOYDSLUBSSLUDSSLUERSLUESSLUGSSLUIG
  SLUITSLUMPSLUMSSLUNGSLUNKSLURPSLURSSLUSHSLUTSSLYLYSLYPESMACKSMAIKSMALLSMALMSMALT
  SMARMSMARTSMASHSMAZESMEARSMEEKSMEERSMEESSMELLSMELTSMETHSMEWSSMICHSMILESMILYSMIRK
  SMITESMITHSMITSSMOCKSMOGSSMOKESMOKYSMOLTSMOOKSMOOTSMORESMOTESMOUSSMOUTSMUGSSMURR
  SMURSSMUSESMUSHSMUTSSMYTHSNABSSNACKSNAFFSNAFUSNAGSSNAILSNAKESNAKYSNAPESNAPSSNAPY
  SNARESNARKSNARLSNARYSNATHSNAWSSNEADSNEAKSNEAPSNEBSSNECKSNEDSSNEERSNEESSNELLSNERP
  SNEWSSNIBSSNICKSNIDESNIFFSNIFTSNIGSSNIPESNIPSSNIPYSNIRLSNIRTSNITESNIVYSNOBSSNOCK
  SNODSSNOEKSNOGASNOGSSNOKESNOODSNOOKSNOOPSNOOTSNOPSSNORESNORKSNORTSNOTSSNOUTSNOWK
  SNOWLSNOWSSNOWYSNUBSSNUCKSNUFFSNUGSSNUMSSNUPSSNURLSNURPSNURSSNURTSOAKSSOAKYSOAMS
  SOAPSSOAPYSOARSSOARYSOBBYSOBERSOCESSOCHTSOCIISOCKSSOCKYSOCLESOCOSSODASSODDYSODIC
  SODIOSODYSSOFARSOFASSOFTASOFTSSOFTYSOGERSOGETSOGGYSOHOSSOILSSOILYSOJASSOKASSOKEN
  SOKESSOLANSOLARSOLASSOLAYSOLDISOLDOSOLDSSOLEASOLENSOLERSOLESSOLIDSOLIOSOLISSOLOD
  SOLONSOLOSSOLUMSOLVESOMALSOMASSOMESSOMMASONARSONDSSONGSSONGYSONICSONKSSONLYSONNY
  SONSSSONSYSOOKSSOOKYSOOLSSOONSSOORDSOOTHSOOTSSOOTYSOPESSOPHSSOPHYSOPORSOPPYSORAL
  SORASSORBSSORDASOREESORESSORGOSORISSORNSSORRASORRYSORTSSORTYSORUSSORVASORYSSOSHS
  SOSOSSOSSSSOTIESOTOLSOTSSSOUDSSOUGHSOULSSOULYSOUMSSOUNDSOUPSSOUPYSOURSSOURYSOUSE
  SOUTHSOWANSOWARSOWELSOWERSOWLESOWLSSOWNSSOWSESOWTESOWTSSOYASSOZINSPACESPACKSPACY
  SPADESPADSSPAERSPAESSPAHISPAIDSPAIKSPAKSSPALDSPALESPALLSPALTSPAMSSPANESPANGSPANK
  SPANNSPANSSPARESPARKSPARMSPARSSPARTSPARYSPASMSPATESPATSSPAVESPAWNSPAYSSPEAKSPEAL
  SPEANSPEARSPECESPECKSPECSSPEDSSPEEDSPEELSPEENSPEERSPELKSPELLSPELTSPENDSPENTSPEOS
  SPERMSPETSSPEWSSPEWYSPEXSSPICASPICESPICKSPICYSPIEDSPIELSPIERSPIFFSPIGSSPIKESPIKY
  SPILESPILLSPILTSPINASPINESPINKSPINSSPINYSPIRESPIROSPIRTSPIRYSPISESPITESPITSSPITZ
  SPIVSSPLATSPLAYSPLETSPLITSPODESPOILSPOKESPOKYSPOLESPONGSPOOFSPOOKSPOOLSPOOMSPOON
  SPOORSPOOTSPORESPORSSPORTSPOSHSPOTSSPOUTSPRADSPRAGSPRATSPRAYSPREESPRETSPREWSPRIG
  SPRITSPRODSPRUESPRUGSPRYSSPUDSSPUGSSPUKESPUMESPUMYSPUNGSPUNKSPUNSSPURLSPURNSPURS
  SPURTSPUTASPUTSSPYERSQUABSQUADSQUAMSQUATSQUAWSQUIBSQUIDSQUINSQUITSRUTISTAABSTABS
  STACKSTADESTAFFSTAGESTAGSSTAGYSTAIASTAIDSTAINSTAIOSTAIRSTAKESTALESTALKSTALLSTAMP
  STAMSSTANDSTANESTANGSTANKSTAPSSTARESTARKSTARNSTARSSTARTSTARYSTASHSTATESTAUKSTAUN
  STAUPSTAVESTAWNSTAWSSTAYSSTCHISTEADSTEAKSTEALSTEAMSTEANSTECHSTEEDSTEEKSTEELSTEEN
  STEEPSTEERSTEGSSTEIDSTEINSTELASTELESTELLSTEMASTEMSSTENDSTENGSTENOSTENSSTENTSTEPS
  STEPTSTERESTERISTERKSTERNSTEROSTERTSTETSSTEWSSTEWYSTEYSSTIBSSTICHSTICKSTIDSSTIFE
  STIFFSTILESTILLSTILTSTIMESTIMSSTIMYSTINESTINGSTINKSTINTSTIONSTIPESTIRKSTIRPSTIRS
  STITESTITHSTIVESTIVYSTOASSTOATSTOBSSTOCKSTODSSTOEPSTOFFSTOFSSTOGASTOGSSTOGYSTOIC
  STOKESTOLASTOLESTOMASTOMPSTONDSTONESTONGSTONYSTOODSTOOFSTOOKSTOOLSTOONSTOOPSTOOT
  STOPASTOPESTOPSSTORESTORKSTORMSTORYSTOSHSTOSSSTOTSSTOUNSTOUPSTOURSTOUTSTOVESTOWS
  STRADSTRAESTRAGSTRAMSTRAPSTRASSTRAWSTRAYSTREESTRESSTRETSTREWSTREYSTRIASTRIDSTRIG
  STRIPSTRITSTRIXSTROMSTROPSTROWSTROYSTRUBSTRUESTRUMSTRUTSTRUVSTUBBSTUBSSTUCKSTUDE
  STUDSSTUDYSTUESSTUFFSTUGSSTULLSTULMSTUMPSTUMSSTUNGSTUNKSTUNSSTUNTSTUPASTUPESTUPP
  STURKSTURTSTUSSSTUTSSTYANSTYCASTYLESTYLOSUADESUANTSUAVESUBAHSUBERSUCCISUCHSSUCKS
  SUCRESUDDSSUDDYSUDSSSUDSYSUEDESUERSSUETSSUETYSUFFSSUGANSUGARSUGHSSUGISSUIDSSUINE
  SUINGSUINTSUISTSUITESUITSSUITYSUJISSULDSSULEASULFASULKASULKSSULKYSULLASULLSSULLY
  SUMACSUMPHSUMPSSUNESSUNGSSUNKSSUNNSSUNNYSUNTSSUNUPSUPASSUPERSUPESSURAHSURALSURAS
  SURATSURDSSURESSURFSSURFYSURGESURGYSURLYSURMASURRASUSISSUSUSSUTORSUTRASUUMSSUWES
  SWABSSWACKSWADSSWAGESWAGSSWAINSWALESWAMISWAMPSWAMSSWANGSWANKSWANSSWAPESWAPSSWARD
  SWARESWARFSWARMSWARTSWASHSWATHSWATSSWAYSSWEALSWEARSWEATSWEEPSWEERSWEETSWEGOSWELL
  SWELPSWELTSWEPSSWEPTSWERDSWICKSWIFTSWIGSSWILESWILLSWIMSSWIMYSWINESWINGSWINKSWIPE
  SWIPYSWIRDSWIRESWIRLSWISHSWISSSWITHSWIZSSWOBSSWOMSSWOONSWOOPSWORDSWORESWORNSWOSH
  SWOTSSWOWSSWUMSSWUNGSWURESYCEESYCESSYLIDSYLPHSYLVASYNCHSYNCSSYNESSYNODSYRESSYRMA
  SYRTSSYRUPTAARSTABBYTABESTABETTABICTABIDTABLATABLETABOGTABOOTABORTABUSTABUTTACHE
  TACHSTACITTACKSTACKYTACSOTACTSTADESTAELSTAENSTAFFYTAFIATAFTSTAGGYTAGUATAHASTAHIL
  TAHINTAHRSTAHUATAICHTAIGATAILSTAILYTAINSTAINTTAIPOTAIRNTAISETAITSTAKARTAKENTAKER
  TAKESTAKINTAKTSTAKYRTAKYSTALAKTALAOTALARTALASTALCSTALDSTALEDTALERTALESTALISTALKS
  TALKYTALLSTALLYTALMATALONTALUKTALUSTAMASTAMBOTAMERTAMESTAMISTAMMYTAMPSTANAKTANAN
  TANASTANESTANGATANGITANGOTANGSTANGYTANHATANHSTANIATANKATANKSTANOATANSYTANTITANZY
  TAPASTAPENTAPERTAPESTAPETTAPIATAPIRTAPISTAPOATAPPATAPSSTAPULTAPUSTAQUATARAFTARAS
  TARAUTARDYTAREATARESTARFATARGETARIETARINTARISTARNSTAROCTAROKTAROSTAROTTARPSTARRI
  TARRSTARRYTARSETARSITARSSTARTSTARVETASCOTASHSTASKSTASSETASSSTASTETASTYTASUSTATER
  TATESTATHSTATIETATOUTATTATATTYTATUSTAULATAUMSTAUNSTAUNTTAUPETAUPOTAURSTAUTSTAVER
  TAVESTAWASTAWERTAWIETAWNSTAWNYTAWPITAWSETAWSSTAXEDTAXERTAXISTAXONTAXORTAXYSTAYER
  TAYIRTAYRATAZIATCHAITCHESTCHUSTEACHTEADSTEAERTEAEYTEAKSTEALSTEAMSTEANSTEAPSTEARS
  TEARTTEARYTEASETEASYTEATSTEATYTEAVETEAZETECASTECHSTECHYTECKSTECONTECUMTEDGETEELS
  TEEMSTEENSTEENYTEERSTEESTTEETHTEETSTEETYTEFFSTEGUATEILSTEINDTEJONTEJUSTEKKETEKYA
  TELARTELESTELICTELISTELLSTELLTTELTSTELYNTEMANTEMBETEMINTEMPITEMPOTEMPSTEMPTTEMSE
  TENAITENCHTENDSTENETTENGSTENGUTENIOTENNETENONTENORTENSETENTHTENTSTENTYTEPALTEPEE
  TEPIDTEPORTERAPTERASTEREKTEREUTERMATERMSTERNATERNETERNSTERPSTERRYTERSETERZOTESTA
  TESTETESTSTESTYTETCHTETELTETESTETHSTETRATEUKSTEWELTEWERTEWITTEWLYTEXTSTHACKTHANA
  THANETHANKTHANSTHARFTHARMTHARSTHATNTHATSTHAVETHAWNTHAWSTHAWYTHEAHTHEATTHEBSTHECA
  THEEKTHEERTHEESTHEETTHEFTTHEGNTHEIRTHEMATHEMETHEMSTHENSTHEOWTHERETHERMTHESETHETA
  THEWSTHEWYTHEYSTHICKTHIEFTHIGHTHIGSTHILKTHILLTHINETHINGTHINKTHINSTHIOLTHIOSTHIRD
  THIRLTHIRSTHIRTTHISNTHISSTHOBSTHOFSTHOFTTHOKETHOLETHOLITHONETHONGTHONSTHOOMTHOOS
  THORETHORNTHOROTHORPTHORTTHOSETHOUSTHOWSTHOWTTHRAMTHRAPTHRAWTHREETHREWTHRIPTHROB
  THROETHROSTHROUTHROWTHRUMTHRUVTHUDSTHUGSTHULRTHUMBTHUMPTHUNGTHUOCTHURLTHURMTHURT
  THUSSTHYMETHYMYTIANGTIAOSTIARATIARSTIBBYTIBETTIBEYTIBIATICALTICCATICERTICESTICKS
  TICKYTICULTIDALTIDDYTIDEDTIDESTIDYSTIEDSTIENSTIERSTIFFSTIFFYTIFTSTIGERTIGESTIGHT
  TIKKATIKORTIKURTILDETILEDTILERTILESTILLSTILLYTILTHTILTSTILTYTIMARTIMBETIMBOTIMED
  TIMERTIMESTIMIDTIMONTIMORTINCTTINDSTINEATINEDTINESTINGETINGITINGSTINKSTINNYTINTA
  TINTSTINTYTINYSTIPESTIPLETIPPYTIPSYTIPUPTIREDTIRERTIRESTIRLSTIRMATIRRSTIRVETISAR
  TITARTITERTITESTITHETITISTITLETITRETITTYTIVERTIVYSTIZASTIZZYTLACOTMEMATOADSTOADY
  TOASTTOATSTOBESTOBYSTOCKSTOCOSTODAYTODDYTODESTODYSTOEDSTOFFSTOFFYTOFTSTOFUSTOGAS
  TOGSSTOGTSTOGUETOHERTOHOSTOILSTOISETOITSTOITYTOKAYTOKENTOKESTOKOSTOLANTOLDOTOLDS
  TOLESTOLLSTOLLYTOLTSTOLUSTOLYLTOMANTOMBETOMBSTOMESTOMINTOMMYTONALTONEDTONERTONES
  TONGATONGSTONICTONKSTONUSTONYSTOOKSTOOLSTOOMSTOONSTOOPSTOOSHTOOTHTOOTSTOPAZTOPEE
  TOPERTOPESTOPHSTOPIATOPICTOPISTOPOSTOPPYTOPSLTOPSSTOQUETORAHTORALTORANTORASTORCH
  TORCSTOREDTORESTORICTORIITORMATORNSTOROSTORSETORSKTORSOTORTATORTSTORUSTORVETORYS
  TOSHSTOSHYTOSSSTOSSYTOSTSTOSYSTOTALTOTEMTOTERTOTESTOTOSTOTTYTOTUMTOTYSTOUCHTOUGH
  TOUGSTOULDTOUPSTOURNTOURSTOUSETOUSYTOUTSTOVARTOWAITOWANTOWDSTOWELTOWERTOWNSTOWNY
  TOWYSTOXASTOXICTOXINTOXONTOYERTOYONTOZEETOZERTOZESTRACETRACKTRACTTRADETRADYTRAGI
  TRAGSTRAHSTRAIKTRAILTRAINTRAITTRAMATRAMETRAMPTRAMSTRANKTRANTTRAPSTRASHTRASSTRASY
  TRAVETRAWLTRAYSTREADTREATTREEDTREENTREESTREEYTREFSTREKSTRENDTRESSTRESTTRETSTREWS
  TREYSTRIADTRIALTRIBETRICATRICETRICKTRIEDTRIERTRIFATRIGSTRIKETRILLTRIMSTRINETRINK
  TRINSTRIORTRIOSTRIPETRIPSTRIPYTRISTTRITETROATTROCATROCKTROCOTRODETRODSTROFTTROGS
  TROKETROLLTROMPTRONATRONCTRONETRONSTROOPTROOTTROPETROTHTROTSTROUTTROVETROWSTROYS
  TRUBSTRUBUTRUCETRUCKTRUERTRUESTRUFFTRUGSTRULLTRULYTRUMPTRUNKTRUNSTRUSHTRUSSTRUST
  TRUTHTRYMATRYPATRYPSTRYSTTRYTSTSARSTSERETSIASTSINETSUBATSUBOTSUNSTUANSTUARNTUART
  TUATHTUBAETUBALTUBARTUBASTUBBATUBBYTUBERTUBESTUBIGTUBIKTUCKSTUCKYTUCUMTUDELTUFAN
  TUFASTUFFSTUFTSTUFTYTUGUITUIKSTUISMTUKESTUKRATULASTULESTULIPTULLETULSITUMESTUMID
  TUMMYTUMORTUMPSTUNASTUNCATUNDSTUNEDTUNERTUNESTUNGOTUNGSTUNICTUNKSTUNNATUNNYTUNOS
  TUNUSTUNYSTUPEKTUPIKTUQUETURBOTURBSTURCOTURDSTURFSTURFYTURGYTURIOTURKSTURMATURMS
  TURNSTURPSTURRSTURSETURUSTUSHSTUSKSTUSKYTUTEETUTESTUTHSTUTINTUTLYTUTORTUTSSTUTTI
  TUTTYTUTUSTUWISTUZASTWAESTWAINTWALETWALSTWALTTWANGTWANKTWANTTWASSTWATSTWAYSTWEAG
  TWEAKTWEEDTWEEGTWEELTWEENTWEESTWEETTWEILTWERETWERPTWICETWICKTWIGSTWILLTWILTTWINE
  TWINKTWINSTWINYTWIRETWIRKTWIRLTWISTTWITETWITSTWIXTTYDIETYEESTYINGTYKENTYKESTYLUS
  TYMPSTYNDSTYPALTYPERTYPESTYPICTYPOSTYPPSTYPYSTYRESTYROSTYSTEUANGSUAYEBUCKIAUDALS
  UDASIUDDERUDELLUGLYSUHLANUHLLOUILYSUINALUKASEULCERULEMAULEXSULLASULLERULMICULMIN
  ULMOSULNADULNAEULNARULNASULOIDULTRAULUASULUHIULULUUMBELUMBERUMBLEUMBOSUMBRAUMIAK
  UMIRIUMPHSUMPTYUNACTUNADDUNALSUNAMOUNAPTUNARKUNARMUNARYUNAUSUNBAGUNBARUNBAYUNBED
  UNBESUNBETUNBIDUNBITUNBOGUNBOWUNBOXUNBOYUNBUDUNCAPUNCASUNCIAUNCISUNCLEUNCOSUNCOY
  UNCUSUNCUTUNDAMUNDENUNDERUNDESUNDIDUNDIGUNDIMUNDOGUNDONUNDOSUNDRYUNDUBUNDUEUNDUG
  UNDYEUNDYSUNEYEUNFARUNFEDUNFEWUNFITUNFIXUNFURUNGAGUNGETUNGKAUNGODUNGOTUNGUMUNHAD
  UNHAPUNHATUNHEXUNHIDUNHITUNHOTUNIATUNICEUNIESUNIFYUNINNUNIONUNIOSUNITEUNITSUNITY
  UNJAMUNKEDUNKENUNKETUNKEYUNKIDUNKINUNLAPUNLAWUNLAYUNLEDUNLETUNLIDUNLIEUNLITUNMAD
  UNMANUNMETUNMEWUNMIXUNNEWUNODEUNOILUNOLDUNORNUNOWNUNPEGUNPENUNPINUNPOTUNPUTUNRAM
  UNRAYUNREDUNRIDUNRIGUNRIPUNROWUNRUNUNSADUNSAYUNSEEUNSETUNSEWUNSEXUNSHYUNSINUNSLY
  UNSONUNSTYUNSUNUNTAPUNTARUNTAXUNTIEUNTILUNTINUNTOPUNTOSUNTZSUNURNUNUSEUNWANUNWAX
  UNWEBUNWEDUNWETUNWIGUNWONUNZENUNZESUPARMUPASSUPBARUPBAYUPBIDUPBUYUPCRYUPCUTUPDOS
  UPDRYUPEATUPENDUPFLYUPGETUPGOSUPHERUPJETUPLASUPLAYUPLEGUPMIXUPONSUPPERUPPOPUPRID
  UPRIPUPRUNUPSETUPSEYUPSITUPSUNUPSUPUPTIEUPWAXUPWAYURALIURALSURANSURAOSURAREURARI
  URASEURATEURBANURBICURDEEURDESUREALUREASUREDOUREICUREIDURENTURGERURGESURIALURICS
  URINEURITEURLARURLEDURMANURNAEURNALURNASURSALURSONURSUKURUBUURUCUURUSSURVASUSAGE
  USARAUSARSUSEDSUSEESUSENTUSERSUSHERUSNEAUSNICUSQUEUSTERUSUALUSUREUSURPUSURYUTAIS
  UTASSUTCHSUTCHYUTEESUTERIUTICKUTILEUTRUMUTSUKUTTERUTUMSUVALSUVATEUVEALUVEASUVICS
  UVIDSUVIOLUVITOUVROUUVULAUVVERUZANSUZARAVACHEVACOAVADESVADYSVAGALVAGASVAGESVAGUE
  VAGUSVAILSVAINSVAIREVAIRSVAIRYVAJRAVAKIAVAKILVALESVALETVALIDVALISVALLSVALORVALSE
  VALUEVALVAVALVEVALYLVAMPSVANEDVANESVANGSVAPIDVAPORVARANVARASVARDYVARECVARESVARIS
  VARIXVARNAVARUSVARVEVARYSVASALVASASVASESVASTSVASTYVASUSVATICVAUDYVAULTVAUNTVEALS
  VEALYVEDROVEENSVEEPSVEERSVEERYVEILSVEILYVEINSVEINYVELALVELARVELASVELDTVELICVELLS
  VELOSVELTEVELUMVENALVENDSVENIEVENINVENOMVENTSVENUEVERASVERBSVERBYVERDSVEREKVERGE
  VERGIVERISVERREVERSEVERSOVERSTVERTSVERVEVERYSVESTSVETASVETCHVETOSVEUVEVEXEDVEXER
  VEXILVEXTSVIALSVIANDVIBEXVIBIXVICARVICESVIDEOVIDRYVIDYAVIERSVIEWSVIEWYVIFDAVIGAS
  VIGIAVIGILVIGORVIJAOVILASVILESVILLAVILLEVILLSVIMENVINALVINASVINEAVINEDVINERVINES
  VINICVINNYVINOSVINTAVINTSVINYLVINYSVIOLAVIOLSVIPERVIRALVIREOVIRESVIRGAVIRIDVIRLS
  VIRONVIRTUVIRUSVISASVISESVISIEVISITVISNEVISONVISORVISTAVISTOVITALVITASVITTAVIUVA
  VIVASVIVAXVIVERVIVESVIVIDVIXENVLEISVOARSVOCALVODKAVOETSVOGUEVOICEVOIDSVOILEVOLAR
  VOLESVOLETVOLTSVOLVAVOMERVOMITVOTALVOTASVOTERVOTESVOUCHVOUGEVOWEDVOWELVOWERVRAIC
  VUGGYVULNSVULVAVYINGWAAGSWAAPAWAARSWABBYWABESWACESWACKEWACKSWACKYWADDYWADERWADES
  WADISWADNAWAEGSWAERSWAFERWAFFSWAFTSWAFTYWAGEDWAGERWAGESWAGGYWAGONWAHOOWAIFSWAIKS
  WAILSWAILYWAINSWAIRDWAISEWAISTWAITSWAIVEWAKANWAKASWAKENWAKERWAKESWAKFSWAKIFWAKON
  WAKYSWALEDWALERWALESWALISWALKSWALLSWALLYWALSHWALTHWALTSWALTZWAMELWAMESWAMPSWAMUS
  WANDSWANDYWANEDWANESWANGAWANGSWANLEWANLYWANNYWANTSWANTYWANYSWAPPSWARCHWARDSWARES
  WARFSWARKSWARLSWARLYWARMSWARNSWARNTWARPSWARSEWARSTWARTHWARTSWARTYWARVEWARYSWASEL
  WASESWASHSWASHYWASNTWASPSWASPYWASTEWASTSWASTYWATAPWATCHWATERWATHSWATTSWAUCHWAUFS
  WAUGHWAULSWAUNSWAUPSWAURSWAUVEWAVEDWAVERWAVESWAVEYWAVYSWAWAHWAWASWAXENWAXERWAXYS
  WAYSSWEAKSWEAKYWEALDWEALSWEAMSWEANSWEARSWEARYWEAVEWEBBYWEBERWECHTWEDESWEDGEWEDGY
  WEEDAWEEDSWEEDYWEEKSWEELSWEENSWEENYWEEPSWEEPYWEESHWEETSWEEZEWEFTSWEFTYWEIGHWEIRD
  WEIRSWEISMWEKASWEKAUWEKISWELDSWELKSWELLSWELLYWELSHWELSSWELTSWENCHWENDEWENDSWENES
  WENNYWENTSWEPTSWERESWERFSWERISWERTSWESESWESTEWESTSWESTYWETASWETLYWEVESWEVETWHACK
  WHALEWHALMWHALPWHALYWHAMEWHAMPWHAMSWHANDWHANGWHANKWHANSWHAPSWHAREWHARFWHARLWHARP
  WHARSWHARTWHASEWHATAWHATSWHAUKWHAUPWHAURWHAUSWHEALWHEAMWHEATWHEELWHEEMWHEENWHEEP
  WHEERWHEESWHEFTWHEINWHEKIWHELKWHELMWHELPWHENSWHEREWHETSWHEWLWHEWSWHEWTWHEYSWHIBA
  WHICHWHICKWHIDSWHIFFWHIFTWHIGSWHILEWHILKWHILLWHILSWHIMSWHINEWHINGWHINSWHINYWHIPS
  WHIPTWHIRLWHIRSWHISHWHISKWHISPWHISTWHITEWHITSWHITYWHIZSWHOASWHOLEWHOMSWHONEWHOOF
  WHOOPWHOOSWHOPSWHOREWHORLWHORTWHOSEWHUDSWHUFFWHULKWHUNSWHUPSWHUSHWHUTEWHUZSWHYOS
  WICESWICHTWICKSWICKYWIDDYWIDENWIDESWIDOWWIDTHWIDUSWIELDWIFESWIFIEWIGANWIGGYWIGHT
  WILDSWILESWILGAWILKSWILLSWILLYWILTSWILYSWIMESWIMPSWINCEWINCHWINDSWINDYWINEDWINER
  WINESWINGSWINGYWINKSWINLYWINNAWINTSWINYSWINZEWIPERWIPESWIPSSWIRDSWIREDWIRERWIRES
  WIRLSWIRRAWIRRSWIRYSWISENWISERWISESWISHAWISHSWISHTWISPSWISPYWISSEWISSSWISTEWISTS
  WITANWITCHWITESWITHEWITHSWITHYWITTYWIVERWIVESWIZENWLOKAWOADSWOADYWOAKSWOALDWOANS
  WODESWODGEWODGYWOFTSWOIBEWOKASWOKESWOLDSWOLDYWOLFSWOLVEWOMANWOMBSWOMBYWONESWONGA
  WONGSWONKYWONNAWONTSWOODSWOODYWOOERWOOFSWOOFYWOOLDWOOLSWOOMSWOONSWOOSHWOOTZWOOZY
  WOPSSWORDSWORDYWORESWORKSWORKYWORLDWORMSWORMYWORNSWORRYWORSEWORSTWORTHWORTSWOTES
  WOTSSWOUCHWOUFSWOUGHWOULDWOUNDWOVENWOVESWOWTSWRACKWRAMPWRANGWRANSWRAPSWRATHWRAWL
  WRAWSWREAKWREATWRECKWRENSWRESTWRICKWRIDEWRIEDWRIERWRIGSWRINGWRISTWRITEWRITHWRITS
  WRIVEWROKEWRONGWROTEWROTHWROXSWRUNGWRYLYWUDGEWUDUSWUGGSWULKSWULLSWUNNAWUSHSWUSPS
  WUSSSWUSTSWUZUSWUZZYWYDESWYKESWYLESWYNDSWYNESWYNNSWYPESWYSONWYSSSWYVERWYVESXEBEC
  XENIAXENONXENYLXERICXOANAXURELXYLANXYLASXYLEMXYLICXYLOLXYLONXYLYLXYRIDXYSTIXYSTS
  YABASYABBIYABBYYABUSYACALYACCAYACHTYADESYAFFSYAGISYAGUAYAHANYAHOOYAIRDYAIRSYAJES
  YAKINYAKKAYALBSYALESYALISYALLAYAMENYAMPAYAMPHYAMPSYANGSYANKSYANKYYAPASYAPLYYAPOK
  YAPPSYAPPYYARAKYARAYYARBSYARDSYARESYARKEYARKSYARLSYARLYYARMSYARNSYARRSYARTHYATES
  YATISYAUDSYAULDYAVASYAWLSYAWNSYAWNYYAWPSYAWSSYAWYSYAYASYCIESYDAYSYEAHSYEANSYEARA
  YEARDYEARNYEARSYEASTYEATSYEDESYEELSYEESSYEGGSYELDSYELKSYELLSYELMSYELPSYELTSYENIS
  YERBAYERBSYERDSYERESYERGAYERKSYERNSYERTHYESESYESOSYESSOYESTSYESTYYETASYETHSYEUKS
  YEUKYYEVENYEZZYYGAPOYIELDYIGHSYILLSYILTSYINCEYINSTYIRDSYIRKSYIRMSYIRNSYIRRSYIRTH
  YITESYOBISYOCCOYOCKSYODELYODHSYOGASYOGHSYOGINYOGISYOICKYOJANYOKELYOKERYOKESYOKYS
  YOLKSYOLKYYOMERYONDSYONTSYOOKSYOOPSYORESYORKSYOTESYOUDSYOUFFYOULSYOUNGYOUPSYOURN
  YOURSYOUSEYOUTHYOUVEYOUZEYOVENYOWIEYOWLSYOWTSYUANSYUCASYUCCAYUCKSYUCKYYUFTSYULAN
  YULESYUMMYYURTAYURTSYUTUSZABRAZABTIZAINSZAMANZAMBOZANTEZANTSZANYSZANZEZAPASZARFS
  ZARPSZATISZAYATZAYINZEALSZEBRAZEBUBZEBUSZEEDSZEINSZEISMZEISTZEMISZEMMIZEMNIZENUS
  ZERDAZEROSZESTSZESTYZETASZIARAZIBETZIEGAZIFFSZIHARZIMBIZIMBSZIMMEZIMMIZINCOZINCS
  ZINGSZINKSZIPPYZIRAIZIRASZIZZSZLOTYZOBOSZOCCOZOEALZOEASZOGANZOGOSZOICSZOIDSZOISM
  ZOISTZOKORZOLLEZOLLSZOMBIZONALZONARZONEDZONESZONICZOOIDZOOKSZOOMSZOONSZORILZORRO
  ZOWIEZUDDAZUZASZYGALZYGASZYGONZYMESZYMICZYMIN
`

// Built once at module load, then every lookup is O(1).
const GUESS_SET = new Set(
  PACKED_GUESSES.replace(/\s/g, '').match(/.{5}/g)
)

export function isValidGuess(word) {
  return GUESS_SET.has(word)
}

export function randomWord() {
  return ANSWERS[Math.floor(Math.random() * ANSWERS.length)]
}

export const GUESS_COUNT = GUESS_SET.size
